kubernetes-csi/external-provisioner

- Dockerfile
- Makefile
- cmd/csi-provisioner/csi-provisioner.go
- extras/docker/Dockerfile
- extras/docker/Dockerfile.builder
- extras/docker/make.sh
* kubeconfig was always being set from the default flags, and so
it was not noticing to use the incluster flags.
* Name of the image is now csi-provisioner not csi-provision
* Added alpine based Dockerfile building to reduce image from 300MB
to 40MB
Signed-off-by: Luis Pabón <luis@portworx.com>
> Fixes needed to start the provisioner

- cmd/csi-provisioner/csi-provisioner.go
This patch remove the duplicate error judgment code when instancing client set.
> Remove duplicate error judgment

- pkg/controller/controller.go
Closes:https://github.com/kubernetes-csi/external-provisioner/issues/23
Adding population of PV's annotations with volume attributes.
> Adding to PV's annotation volume attributes

- README.md
This patch changes "_output/hostpath" to "_output/hostpathplugin"
in the README on how to run hostpath driver.
> Fix hostpathplugin path in README

- deploy/kubernetes/statefulset.yaml
This patch modifies the statefulset example to include proper roles. It is also required to run the components in the kube-system namespace.
> Updating StatefulSet to support clusters using RBAC

- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
This patch makes change to volume naming so that both prefix and uuid length are configurable. Some storage systems have max limits to volume naming, so making these fields configurable allows much shorter names if necessary. It is also helpful to use different prefixes to make storage administration easier.
> Volume Naming Prefix and UUID Length Parameters

- pkg/controller/controller.go
PV's NodePublishSecretRef should have non nil value only when storage class has a valid reference to existing Secret object.
> provisioner Secret fix

- pkg/controller/controller.go
PluginCapability update for external-provisioner
@jsafrane @saad-ali
> PluginCapability update for external-provisioner

- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
This PR addresses two issues:
1. For a specific PVC, external provisioner always generates the same PV name
2. Implements Exponential Backoff for long operations like CreateVolume
Now there are 2 timers, one short timeout which is enforced by the context, second is exponential backoff timer.
This functionality will require support from the driver. It needs to detect if the request to CreateVolume comes for already initiated volume and then check for completion periodically, once it is completed it should return CreateVolumeResponse struct. 
Fixes https://github.com/kubernetes-csi/external-provisioner/issues/63
> Persistent name and Exponential backoff

- pkg/controller/controller.go
- pkg/controller/controller_test.go
PV currently just passes capacity bytes through from the PVC. This might differ from the number of bytes actually provisioned by the plugin. The Plugin response capacity should be used as the source of truth for the PV Capacity.
Fixes: #48
> Bugfix: PV should use capacity bytes returned by plugin, not PVC bytes

- pkg/controller/controller.go
- pkg/controller/controller_test.go
> Made storage shown in PV more readable

- Makefile
- cmd/csi-provisioner/csi-provisioner.go
+ log the version on startup.
It follows https://github.com/kubernetes-csi/external-attacher/pull/47
Fixes: #80
> Add -version argument to show version.

- pkg/controller/controller_test.go
> Add controller provision tests

- .travis.yml
- Makefile
/assign @jsafrane @lpabon 
travis.ci needs to be locked to 1.10.3 because previously it was defaulting to a beta 1.11.x version that had `go fmt` issues
> Lock travis.ci go version to 1.10.3 and add soft tag to revision

- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
Fixes: #115
Changes default behavior of volume name to non-truncating. If the flag is set we will remove all dashes and truncate volume name.
/assign @cduchesne @saad-ali 
I believe this should also be cherry-picked to v0.3.0 container as we don't want default behavior of naming to jitter between versions.
> Change default volume name behavior to non-truncating

- pkg/controller/controller.go
- pkg/controller/controller_test.go
Currently, the code is hardcoded to always send the AccessMode of SINGLE_WRITER to the CSI plugin even though the request from the PVC is to have a ReadWriteMany.
Closes #132 
Signed-off-by: Luis Pabón <luis@portworx.com>
> Support all Kubernetes access modes

- .gitignore
- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/topology.go
- pkg/controller/topology_test.go
Creating a PR for early review.
I have a local working prototype. The hope is each of these PRs introduce a feature whose implementation is as close to the final form as possible.
@jsafrane @msau42 @saad-ali @ddebroy
Features (some of these need more refinement but core logic is there):
> Topology support

- pkg/controller/controller.go
If the snapshot is currently being deleted, the deletionTimestamp is
set, and provisioner should not try to create the volume in this case.
> Add the check for deleting snapshot while creating volume

- pkg/controller/controller.go
- pkg/controller/topology.go
- pkg/controller/topology_test.go
If immediate volume binding mode is set and the PVC follows StatefulSet naming format, then the provisioner will choose, as the first segment in preferred topology, a segment from requisite topology based on the relevant parts of the PVC name that ensures an even spread of topology across the StatefulSet's volumes.
The logic around determining the StatefulSet naming format and obtaining a hash and index is identical to the logic in pkg/volume/util/util.go Kubernetes main tree.
Fixes: https://github.com/kubernetes-csi/external-provisioner/issues/143
cc @msau42 @verult
> Evenly spread volumes of a StatefuleSet across nodes based on topology

- deploy/kubernetes/rbac.yaml
The files worked fine in automated testing, but kubectl complains
about the missing apiGroup.
> rbac: fix kubectl validation error

- .gitignore
- pkg/controller/topology.go
I had an issue that is obscure to debug without `requisite` being logged when matchLabelExpressions key mismatches for `allowedTopologies` in storage class.
> Update log message for help debugging

- pkg/controller/controller.go
- pkg/controller/controller_test.go
Below three logics are implemented to add Block volume support to CSI provisioner:
1. Add ```SupportsBlock``` that properly returns whether Storage
Provider's plugin supports block (this is checked
by using ```ValidateVolumeCapabilities```),
2. Pass ```BlockVolume``` instead of ```MountVolume``` to ```CreateVolume```
if ```volumeMode``` is set to be Block on ```Provision```,
3. Set ```volumeMode``` to PV returned by ```Provision```.
Also, below 4 test cases for TestSupportsBlock and 2 test cases for TestProvision
are added.
```TestSupportsBlock```:
1. ```ValidateVolumeCapabilities``` return ```(true, nil)``` case: return ```true``` expected
2. ```ValidateVolumeCapabilities``` return ```(false, nil)``` case: return ```false``` expected
3. ```ValidateVolumeCapabilities``` return ```(true, …
```
> Add Block volume support for CSI provisioner

- README.md
- cmd/csi-provisioner/csi-provisioner.go
Resolves #162 
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>
> Remove provisioner argument, update README

- deploy/kubernetes/rbac.yaml
Related: #164
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>
> Don't provide access to Secrets in default RBAC

- deploy/kubernetes/rbac.yaml
Needed by topology aware provisioning.
Thanks @pohly for heads up.
> Add RBAC rules for CSINodeInfo

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go
- vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/volume.go
Cherry pick of #209 on release-1.0.
#209: update kubernetes-sigs/sig-storage-lib-external-provisioner
> Automated cherry pick of #209: update kubernetes-sigs/sig-storage-lib-external-provisioner

- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
Provisioner should not ask for it every time, it should not change during driver container lifetime.
> Cache driver name

- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
We should use exponential backoff from the provisioner library. It will react more quickly when a PVC is deleted and it won't occupy a worker thread.
I verified that #63 is still fixed, the provisioner consistently uses `pvc-<uid>` as CO-supplied volume name for idempotency.
Fixes: #101 #154
> Remove internal retry loop

- cmd/csi-provisioner/csi-provisioner.go
Fixes https://github.com/kubernetes-csi/external-provisioner/issues/227
> Add --timeout parameter

- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
I found the variable `csiEndpoint` in function NewCSIProvisioner has never been used. So, I think it is better to remove it.
> Remove the unused varible

- pkg/controller/controller.go
This Pr 
1) replaced some string variables with consts
2) re-organized the imports
> Replace some string variables with consts and re-organize the imports

- Gopkg.lock
- Gopkg.toml
- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
- vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer.go
- vendor/github.com/kubernetes-csi/csi-lib-utils/release-tools/LICENSE
- vendor/github.com/kubernetes-csi/csi-test/driver/mock.go
The result should be the same as in https://github.com/kubernetes-csi/external-attacher/pull/123
> Use Connection() from util package

- cmd/csi-provisioner/csi-provisioner.go
It should be CSI call timeout, not deprecated connection timeout.
cc @pohly
> Fix GetDriverName timeout

- cmd/csi-provisioner/csi-provisioner.go
The provisioner should not exit on startup when the option is present. We'll remove in some next release.
> Restore '--provisioner' option

- cmd/csi-provisioner/csi-provisioner.go
We haven't found use-case where these parameters should be exposed to users. The provisioner will try indefinitelt to provision/delete a volume.
> Remove configuration of retry count

- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
We don't expect that driver capabilities change when the driver is running. In this PR:
* The provisioner checks capabilities on startup and exits, if the driver does not support dynamic provisioning.
* It caches all capabilities and check the cached values for snapshot and volume topology support when necessary.
edit: This changes behavior of external-provisioner.
Previously, it was running even if the driver did not support dynamic provisioning and created events for all PVCs that it won't provision them. Users could spot this event easily and talk to cluster admin.
Now users will see just "waiting for a volume to be created, either by external provisioner or manually". The provisioner just dies on startup and it's up to cluster admin to find out what's wrong.
> Cache driver capabilities

- pkg/controller/controller.go
- pkg/controller/controller_test.go
The external resizer introduces two StorageClass parameters used by resizing secret: https://github.com/kubernetes-csi/external-resizer/blob/25e836c8513f0d31df3604981f1312f0db376e45/pkg/resizer/csi_resizer.go#L45
The external provisioner should remove these parameters before passing to the driver.
> filter resizer related params from storageclass before passing them to the driver

- Gopkg.lock
- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- vendor/k8s.io/cloud-provider/LICENSE
- vendor/k8s.io/cloud-provider/volume/constants.go
- vendor/k8s.io/csi-translation-lib/LICENSE
- vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
- vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
- vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
- vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
- vendor/k8s.io/csi-translation-lib/translate.go
NOTE 1: The CSI migration provisioning logic here is not directly feature gated. However, the feature flags on the in-tree side sufficiently protects the logic here. This is because the PV controller in-tree will only yield PVCs (for in-tree provisioners) to the external provisioner when the feature flags for CSI migration for a particular plugin is enabled in-tree which in turn will make a plugin advertise `IsMigratedToCSI `: https://github.com/kubernetes/kubernetes/commit/23478f104f6ea26f752f1aae71301b637d2935a5#diff-3f32ad90966ceeb297f57c2a8d726348R1404 
NOTE 2: Unit tests are skipped for now. We need to address https://github.com/kubernetes/kubernetes/issues/74594 to be able to inject unit-tests as desired into the translation framework for unit testing purposes.
Tested e2e with GCE …
> Add dynamic provisioning support for CSI migration scenarios

- cmd/csi-provisioner/csi-provisioner.go
CreateProvisionedPVLimiter will cause the controller to never stop saving PVs to API server until it succeeds. Previously, the controller tried couple of times and then deleted the storage volume (i.e. called
ControllerDeleteVolume).
Fixes: #94
> Do not stop saving PVs to API server

- README.md
- deploy/kubernetes/deployment.yaml
- doc/development.md
- examples/sc.yaml
- Following external-attacher as example.
- Removed #Build and #Test, they were not useful, added short doc/development.md.
- Moved away from StatefulSet to Deployment. Deployment behaves better when a node gets disconnected from the rest of the cluster - new provisioner leader is elected in ~15 seconds, while it may take up to 5 minutes for StatefulSet to start a new replica. (Again, following external-attacher as sample)
> Update README to 1.14

- pkg/controller/topology.go
When the provisioner get csinode err, it would be overrided by parse err.
> Bugfix: get csinode err overrided by parse err

- Gopkg.lock
- Gopkg.toml
- README.md
- cmd/csi-provisioner/csi-provisioner.go
- deploy/kubernetes/rbac.yaml
- vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
- vendor/golang.org/x/sys/unix/mksyscall.go
- vendor/golang.org/x/sys/unix/syscall_darwin.go
- vendor/golang.org/x/sys/unix/types_darwin.go
- vendor/golang.org/x/sys/unix/ztypes_darwin_386.go
- vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
- vendor/golang.org/x/sys/unix/ztypes_darwin_arm.go
- vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
Also adds support for lease based leader election which is highly recommended over endpoints base. Endpoints based will be supported for a few releases for backwards compatibility. 
/assign @msau42 @jsafrane  @xing-yang
> Use leader election library from csi-lib-utils 

- Gopkg.lock
- Gopkg.toml
- vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go
The only new change from 3.0.0beta to 3.0.0 is "Retry if StorageClass not found" https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/38
i would like a new tag so that we can use it here https://github.com/kubernetes/kubernetes/blob/247b8fffb73d2473c68916936ec700304c1605c8/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-provisioner.yaml#L33 and see if it fixes? https://github.com/kubernetes/kubernetes/issues/76166
@msau42
> Update to sig-storage-lib-external-provisioner v3.0.0

- pkg/controller/controller.go
- pkg/controller/controller_test.go
since the struct contains "deprecated" prefix hinting but some of the key is not really deprecated.
so it may confuse us. This is a private struct, it's simple to just rename in Controller and
test file.
224
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
solve misleading struct deprecatedSecretParamsMap 
Fixes #224 
```release-note
NONE
```
> solve misleading struct deprecatedSecretParamsMap

- pkg/controller/controller.go
>
/kind bug
> /kind design
> /kind flake
Deletion of CSI migrated volumes were not getting correctly handled as the translation of the in-tree spec to CSI spec was not being done. This PR performs the translation.
Fixes # https://github.com/kubernetes/kubernetes/issues/77102
Tested with GCE PD with feature flags enabled for CSIMigration and CSIMigrationGCE. 
```
Name:              pvc-faad937e-eb54-49c0-a408-0a6a7d551945
Labels: …
```
> Handle deletion of CSI migrated volumes

- CHANGELOG-1.1.md
- pkg/controller/controller.go
>
/kind bug
> /kind design
> /kind flake
Cherry picks https://github.com/kubernetes-csi/external-provisioner/commit/6b31b6c565f1b78ead865e26f9ad98cc36b52951 to `Release 1.1` branch and updates changelog.
Fixes # https://github.com/kubernetes/kubernetes/issues/77102
As requested in https://github.com/kubernetes-csi/external-provisioner/pull/275#pullrequestreview-235078520
```release-note …
```
> Cherry pick handling of deletion of CSI migrated volumes

- Gopkg.lock
- Gopkg.toml
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
- vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
- vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
- vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
- vendor/k8s.io/csi-translation-lib/translate.go
- vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go
- vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/volume.go
This PR updates the controller to translate the entire storage class when the migration path is hit. This allows us to modify things such as topology, parameters, mount options etc.
/kind feature
/sig storage
Fixes: https://github.com/kubernetes/kubernetes/issues/77235
```release-note
Fixes migration scenarios for Topology, fstype, and accessmodes for the kubernetes.io/gce-pd in-tree plugin
```
> Bump provisioner lib and migration library dependencies. Update migration translation to translate the entire storage class.

- pkg/controller/controller.go
- pkg/controller/controller_test.go
Signed-off-by: Grant Griffiths <ggp493@gmail.com>
/kind feature
* This allows Provision to pass the correct PVC object so that the k8s secrets can be pulled and used during provisioning. 
Fixes #170 
Fixes #233
* I'm still testing this change on my k8s cluster, which is why I've added the WIP tag.
```release-note
Users can now provide a secret name and namespace during provision by passing the correct storage class parameters: "provisioner-secret-name" and "provisioner-secret-namespace"
```
> Add secret support for Provision and Delete from pvc name and namespace

- pkg/controller/controller.go
- pkg/controller/controller_test.go
Backport #274 to release-1.2 branch
/kind feature
**What this PR does / why we need it:**
- This allows Provision to pass the correct PVC object so that the k8s secrets can be pulled and used during provisioning.
- We need this fix in Kubernetes 1.13
**Which issue(s) this PR fixes:**
- Fixes #170
- Fixes #233
Does this PR introduce a user-facing change?:
```release-note
Users can now provide a secret name and namespace during provision by passing the correct storage class parameters: "provisioner-secret-name" and "provisioner-secret-namespace"
```
> [release-1.2] Add secret support for Provision and Delete from pvc name and namespace

- README.md
- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/topology.go
- pkg/controller/topology_test.go
With the current implementation, In delayed binding case, CSI driver is offered
with all nodes topology that are matched with 'selected node' topology keys in
`CreateVolumeRequest.AccessibilityRequirements`. So this allows the driver to
select any node from the passed `preferred/requisite` list to create volume. But this
results in scheduling failure when the volume created on a node other than
Kubernetes selected node.
To address this, introduced new flag "--strict-topology', when set, in case of
delayed binding, the driver is offered with only selected node topology, so that
the driver has to create the volume on this node.
This new flag can be used by drivers that support strict topology for volumes with delayed binding.
/kind bug
/kind design
**What this …
> Introduce new flag - strict-topology

- deploy/kubernetes/deployment.yaml
csi-provisioner service creation was necessary to run external-provisioner
as statefulset, after moving from statefulset to deployment, we no longer need dummy service.
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
```
> Remove dummy service from the deployment

- pkg/controller/controller.go
- pkg/controller/controller_test.go
This PR extends the supported DataSources handled by the
external-provisioner to include PVCs (Clone) and Populators (external
CRDs).
It removes the restriction of of the provisioner erroring when a
DataSource.Kind of anything other than VolumeSnapshot is supplied (the
Kubernetes API currently enforces this anyway via it's verifictaion
checks) and adds handling for a DataSource.Kind of
PersistentVolumeClaim.
Addresses: Issue #172
Does this PR introduce a user-facing change?:
```release-note
Adds the ability to handle PVC as a DataSource to enable cloning for plugins that support it.
```
> Extend allowed DataSources

- pkg/controller/controller.go
- pkg/controller/controller_test.go
Backport #274 to Kubernetes 1.13
/kind feature
**What this PR does / why we need it:**
- This allows Provision to pass the correct PVC object so that the k8s secrets can be pulled and used during provisioning.
- We need this fix in Kubernetes 1.13
**Which issue(s) this PR fixes:**
- Fixes #170
- Fixes #233
Does this PR introduce a user-facing change?:
```release-note
Users can now provide a secret name and namespace during provision by passing the correct storage class parameters: "provisioner-secret-name" and "provisioner-secret-namespace"
```
> [release-1.0] Add secret support for Provision and Delete from pvc name and namespace

- README.md
- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/topology.go
- pkg/controller/topology_test.go
Backport #282 to release-1.2
/kind bug
/kind design
Allows the driver to support delayed binding properly.
Fixes #221 
```release-note
support strict topology for volumes with delayed binding
```
> [release-1.2]  Introduce new flag - strict-topology

- Gopkg.lock
- pkg/controller/controller.go
- pkg/controller/controller_test.go
Backport #274 to 1.1 branch
/kind feature
**What this PR does / why we need it:**
- This allows Provision to pass the correct PVC object so that the k8s secrets can be pulled and used during provisioning.
**Which issue(s) this PR fixes:**
- Fixes #170
- Fixes #233
Does this PR introduce a user-facing change?:
```release-note
Users can now provide a secret name and namespace during provision by passing the correct storage class parameters: "provisioner-secret-name" and "provisioner-secret-namespace"
```
> [release-1.1] Add secret support for Provision and Delete from pvc name and namespace

- CHANGELOG-1.2.md
Used kubernetes release-note tool 
Fixes #
```release-note
NONE
```
> Update 1.2 changelog to follow release tools format

- cmd/csi-provisioner/csi-provisioner.go
/kind bug
**What this PR does / why we need it**: Today there are two leader election processes running - one defined in external-provisioner main, one enabled in the provisioner controller lib by default. I ran into this problem when I set leader election type to lease - the external provisioner tries to do both lease-based and endpoint-based LE.
Also adding the ability to restrict the lock resource to specific namespaces.
Fixes #
```release-note
A new flag --leader-election-namespace is introduced to allow the user to set where the leader election lock resource lives.
```
> Leader election: disable duplicate LE in provisioner lib; add lock namespacing

- cmd/csi-provisioner/csi-provisioner.go
What type of PR is this?
/kind bug
What this PR does / why we need it: Today there are two leader election processes running - one defined in external-provisioner main, one enabled in the provisioner controller lib by default. I ran into this problem when I set leader election type to lease - the external provisioner tries to do both lease-based and endpoint-based LE.
Also adding the ability to restrict the lock resource to specific namespaces.
```release-note
A new flag --leader-election-namespace is introduced to allow the user to set where the leader election lock resource lives.
```
> Cherry-pick of #296: "Leader election: disable duplicate LE in provisioner lib; add lock namespacing"

- cmd/csi-provisioner/csi-provisioner.go
What type of PR is this?
/kind bug
What this PR does / why we need it: Today there are two leader election processes running - one defined in external-provisioner main, one enabled in the provisioner controller lib by default. I ran into this problem when I set leader election type to lease - the external provisioner tries to do both lease-based and endpoint-based LE.
Also adding the ability to restrict the lock resource to specific namespaces.
```release-note
A new flag --leader-election-namespace is introduced to allow the user to set where the leader election lock resource lives.
```
> Cherrypick of #296: "Leader election: disable duplicate LE in provisioner lib; add lock namespacing"

- CHANGELOG-1.3.md
- README.md
Fixes #
```release-note
NONE
```
> Add 1.3 changelog

- pkg/controller/controller.go
- pkg/controller/controller_test.go
>
/kind bug
> /kind design
> /kind flake
current PVC request is sending the PV name while creating a volume from a volume, as per the CSI spec we need to send the volume_id for creation of PVC from another PVC.
Fixes #
```release-note
This PR send the volume_id instead of  PVC Name to the csi-driver in volumeCreate when datasource  is PVC
```
> use volume ID for creating PVC from another PVC

- release-tools/build.make
- release-tools/prow.sh
/kind bug
/kind feature
* Fix issue where sidecars were testing against hostpath canary instead of hostpath stable images
* Update prow to support 1.15 testing
Fixes #
```release-note
NONE
```
> prow updates

- Gopkg.lock
- pkg/controller/controller.go
- pkg/controller/controller_test.go
The provisioner should retry CreateVolume call after a transient error (such as timeout), because the CSI driver may be creating a volume in the background.
Therefore `ProvisionerExt` interface need to be implemented. `ProvisionExt()` returns:
- `Finished`, if it can be 100% sure that the driver is not creating a volume
- `NoChange`, if something (temporarily?) failed before reaching the CSI driver, for example when Kubernetes API server is not reachable.
- `InBackground`, if error returned by the driver (or gRPC) is transient.
/kind bug
Fixes #311
```release-note
Fixed potential leak of volumes after CSI driver timeouts.
```
> Retry provisioning of volumes after transient error

- Gopkg.lock
- pkg/controller/controller.go
- pkg/controller/controller_test.go
This is cherry-pick of #312 into 1.2
---
The provisioner should retry CreateVolume call after a transient error
(such as timeout), because the CSI driver may be creating a volume in the
background.
Therefore ProvisionerExt interface need to be implemented. ProvisionExt()
returns:
- Finished, if it can be 100% sure that the driver is not creating a volume
- NoChange, if something (temporarily?) failed before reaching the CSI
driver, for example when Kubernetes API server is not reachable.
- InBackground, if error returned by the driver (or gRPC) is transient.
```release-note
Fixed potential leak of volumes after CSI driver timeouts.
```
> [1.2] Cherry pick: Retry provisioning of volumes after transient error

- Gopkg.lock
- pkg/controller/controller.go
- pkg/controller/controller_test.go
This is cherry-pick of https://github.com/kubernetes-csi/external-provisioner/pull/312 into 1.3
---
The provisioner should retry CreateVolume call after a transient error
(such as timeout), because the CSI driver may be creating a volume in the
background.
Therefore ProvisionerExt interface need to be implemented. ProvisionExt()
returns:
- Finished, if it can be 100% sure that the driver is not creating a volume
- NoChange, if something (temporarily?) failed before reaching the CSI
driver, for example when Kubernetes API server is not reachable.
- InBackground, if error returned by the driver (or gRPC) is transient.
```release-note
Fixed potential leak of volumes after CSI driver timeouts.
```
> [1.3] Cherry pick: Retry provisioning of volumes after transient error

- pkg/controller/controller.go
- pkg/controller/controller_test.go
>
/kind bug
> /kind design
> /kind flake
According to CSI spec CreateVolume should be able to return capacity = 0, which means it is unknown.
However, provisioner will ignore it.
Fixes #127 
```release-note
CSI driver can return `CreateVolumeResponse` with size 0, which means unknown volume size. 
In this case, Provisioner will use PVC requested size as PV size rather than 0 bytes
```
> fix provision fail when volume size is unknown

- pkg/controller/controller_test.go
/assign @bswartz @jsafrane
/kind cleanup
```release-note
NONE
```
> Remove redundant mount options test and fold into normal provisioner test

- pkg/controller/controller.go
- pkg/controller/controller_test.go
This fixes  the  issue in storageclass name comparison for PVC  creation with datasource=PersistanceVolumeClaim
>
/kind bug
> /kind design
> /kind flake
Fixes #308
```release-note
None
```
> fix pvc and source PVC storageclass name comparison for pvc datasource

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind bug
Compare storage class string, instead of comparing
the string address.
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
Fixes #308 
Backport from master to 1.3
```release-note
NONE
```
> fix storageclass comparion for pvc datasource

- pkg/controller/controller.go
>
/kind bug
> /kind design
> /kind flake
log PV object with v(5) verbosity.
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
Fixes https://github.com/kubernetes-csi/external-provisioner/issues/329
```release-note
NONE
```
> Improve PV creation logging

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind bug
Need to check VolumeContentSource if creating volume from snapshot
Fixes #280 
```release-note
Checks if volume content source is populated if creating a volume from a snapshot source.
```
> Need to check VolumeContentSource if creating volume from snapshot

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind bug
The provisioner just picks up any in-tree PVC that is related to the CSI Driver and treats it as a "migrated" PVC and continues to provision it. In reality it should use the annotation as a signal on whether the in-tree pv-controller has stood down or not (migrated or not).
/assign @jsafrane @msau42 @ddebroy 
/cc @leakingtapan
Fixes #340
```release-note
Fixes issue where provisioner provisions volumes for in-tree PVC's which have not been migrated
```
> Ignore provisioning for in-tree volumes that have not been migrated

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go
- vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/volume.go
Reverts kubernetes-csi/external-provisioner#212
This required new rbac rules which is not backwards compatible. More discussion at https://github.com/kubernetes-csi/external-provisioner/issues/195#issuecomment-481008688
> Revert "Automated cherry pick of #209: update kubernetes-sigs/sig-storage-lib-external-provisioner"

- CHANGELOG-1.4.md
Fixes #
```release-note
NONE
```
> add 1.4 changelog

- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
Cherry-pick of: https://github.com/kubernetes-csi/external-provisioner/pull/341
/kind bug
/assign @jsafrane @msau42 
/cc @ddebroy @leakingtapan 
```release-note
Fixes issue where provisioner provisions volumes for in-tree PVC's which have not been migrated
```
> Ignore non-migrated in-tree PVC when provisioning

- pkg/controller/controller.go
If I understand [code in `ProvisionExt`](https://github.com/kubernetes-csi/external-provisioner/blob/3184db61ab93bbe588fff4a223bf23c49a5d5937/pkg/controller/controller.go#L374), PVCs that require migrated in-tree provisioner in their StorageClass have their `volume.beta.kubernetes.io/storage-provisioner` annotation set to **CSI driver name**.
Therefore we do not need the provisioner library to listen for PVCs with in-tree provisioner at all and save some (little) CPU in unrelated PVC processing. I keep the check in `ProvisionExt`, just in case.
@ddebroy, PTAL carefuly.
/kind cleanup
```release-note
NONE
```
> Don't process PVCs for in-tree volumes

- pkg/controller/controller.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> Record the error if we fail to get referenced storageclass and secret.

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind bug
```release-note
Added extra verification of source Snapshot and PersistentVolumeClaim before provisioning.
```
> Fix claimRef and shapshotRef checks

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind bug
```release-note
Added extra verification of source Snapshot and PersistentVolumeClaim before provisioning.
```
> 1.3: fix  Fix claimRef and snapshotRef checks

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind bug
```release-note
Added extra verification of source Snapshot before provisioning.
```
> 1.2: Fix snapshotRef checks

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind bug
```release-note
Added extra verification of source Snapshot before provisioning.
```
> 1.0: Fix snapshotRef checks

- Gopkg.lock
- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
- vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
- vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
- vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
- vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
- vendor/k8s.io/csi-translation-lib/translate.go
Bumps the csi-translation-lib to head and makes it injectable. Contains some functional changes - none of which affect the behavior of the external-provisioner (except for the bug fix that did nil checks for Azure: https://github.com/kubernetes/kubernetes/pull/83249)
csi-translation-lib versioning TBA :)
/assign @misterikkit @msau42 
/cc @ddebroy 
/kind cleanup
/kind feature
```release-note
NONE
```
> Bump csi-translation-lib to HEAD

- CHANGELOG-1.3.md
Fixes #
```release-note
NONE
```
> Update 1.3 changelog for 1.3.1

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind bug
```release-note
Added extra verification of source Snapshot before provisioning.
```
> 0.4: Fix snapshotRef checks

- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/topology.go
- pkg/controller/topology_test.go
- vendor/modules.txt
/kind cleanup
Use Node informer instead of hitting the API server for all Node resource request.
Fixes #144
I used the commit from the PR: https://github.com/kubernetes-csi/external-provisioner/pull/327, I can also change that PR to add node informer.
```release-note
NONE
```
cc @msau42 @verult
> Use Node informer to prevent hitting the API server for all time

- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/topology_test.go
/kind cleanup
Fixes #256
```release-note
Use informers for StorageClass
```
> Use informers for StorageClasses lookups

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind feature
Fixes #384
```release-note
Default StorageClass secrets are added:
csi.storage.k8s.io/secret-name: ${pvc.name}
csi.storage.k8s.io/secret-namespace: ${pvc.namespace}
Note: Default secrets for storage class feature does work only when both parameters are added.
```
> issue-384, A single "default" storage class secret is added

- README.md
- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
Co-authored-by: abrden <agustina.barbetta@gmail.com>
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Add PVC metadata to plugin call in the CreateVolume operation for it to be able to query for more information if needed during volume creation.
Fixes #370 
```release-note
* Adds --extraCreateMetadata flag which, when enabled, will inject parameters onto CreateVolume driver requests with PVC and …
```
> add pvc metadata to createvolume req

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind cleanup
There was quite a bit of repetitive code in each test case definition,
this has been cleaned up. Further following changes were done as some failures
during the cleanup were noted,
- Corrected size checks in controller.go, to use sourcePVC size instead
of gRPC payload size for comparison
- Updated fakeClaim in controller_test.go, to reflect correct sourcePVC
size (instead of defaulting to 1Gi for a 1000 byte request)
- Defined and reused a defaultPVCRequest across tests
- Removed unused test case struct elements
- Removed restating default test case parameters per test
- Refactored core test case loop into phases, and removed any duplicate
calls/variables
- Corrected expected RPC calls when sourcePVC size …
> Cleanup and fix, clone unit tests

- README.md
Incorrect documentation for the new feature flag.
No issues currently open for this.
Logs using current docs:
```
unknown flag: --extraCreateMetadata
Usage of /csi-provisioner:
...
--extra-create-metadata              If set, add pv/pvc metadata to plugin create requests as parameters.
...
```
```release-note
NONE
```
> Document correct flag name for --extra-create-metadata

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind bug
This commit adds 6 more tests to the existing unit tests
for creating PVC given a DataSource as another PVC, IOW
cloning feature.
The tests are added in 2 categories,
- When source PVCs Status.Phase is different than,
ClaimBound
- When clone PV source's Status.Phase is other than,
VolumeBound
The tests did open up a code issue, where PV Status was
not checked for VolumeBound status. This is also fixed
in this commit.
Tested using `make test-go` against go compiler
version go1.13.6 linux/amd64
NA, Added to help move clone feature to GA.
- If PV `Spec.ClaimRef` is non-nil, can `Status.Phase` be anything other than bound? IOW, is this test …
> Add more tests for provsionsing from PVC as DataSource

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind cleanup
This PR add checks against the volume mode between source and newly created
clone of a pvc.  If the source PVC does not match the requested volume mode of
the newly created clone the create operation will fail.
```release-note
NONE
```
> Add volumeMode checks to clone operations

- README.md
- cmd/csi-provisioner/csi-provisioner.go
/kind flake
Follow up PR to #422, addressing comment - https://github.com/kubernetes-csi/external-provisioner/pull/422#discussion_r393207897
```release-note
Adde a new flag, `cloning-protection-threads` which defaults to 1,
managing how many threads will simultaneously serve the
`provisioner.storage.kubernetes.io/cloning-protection` finalizer removal
```
> Reduced number of threads for finalizer removal to 1

- pkg/controller/topology.go
- pkg/controller/topology_test.go
/kind feature
**What this PR does / why we need it:**
fixes:- https://github.com/kubernetes-csi/external-provisioner/issues/420
If waitforfirstconsumer is used and if the driver supports multiple topology  keys,
mentioning single key(or less than supported keys) in the storageclass is not working.
The csi-provisioner gets list of all the topology keys from the csinode object
and gets the values for those keys from the node object. Now this key-value term
is matched against the topology mentioned in the storageclass and it should match
entirely which is not correct as even if topology mentioned in the storageclass
is subset of the key-value term supported by the driver, then the node is a valid condidate.
Instead of strictly checking for the equality of the …
> subset of supported topology keys are not working for waitforfirstconsumer

- README.md
- cmd/csi-provisioner/csi-provisioner.go
>
> /kind bug
> /kind design
> /kind flake
This PR removes the `--enable-leader-election`  and `leader-election-type` flag and add `leader-election` flag as other sidecar containers.
Fixes #401
```release-note
This introduces a new flag `leader-election` which is the same as in other sidecar containers and also removes the `enable-leader-election` and `leader-election-type` flag
```
> Make leader-election flag consistent with other sidecar

- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/clone_controller.go
- pkg/controller/clone_controller_test.go
/kind bug
Adds a capability check, to prevent cloning protection from starting, when `CLONE_VOLUME` is not set on the driver.
Fixes #431 
```release-note
NONE
```
> Start clone protection only when capability matches

- .prow.sh
- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/topology.go
- pkg/controller/topology_test.go
/kind feature
This PR updates the external provisioner to use the GA version of the CSINode object.
Fixes #385
```release-note
Use GA version of CSINode object.
```
> Use v1.CSINode in the external-provisioner

- cmd/csi-provisioner/csi-provisioner.go
- deploy/kubernetes/rbac.yaml
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/topology_test.go
This change prevents calling DeleteVolume on the CSI plugin for volumes that are still attached to a kubernetes node.
/kind bug
Currently, external-provisioner does not check if a volume is attached to a node before trying to delete it. 
This can happen when there's a race between Pod and PVC deletion (like deleting a ns). 
NOTE: PVC protection does not apply here because the Pod is deleted from k8s, but the volume is still attached. 
Based on discussion in https://github.com/kubernetes/kubernetes/issues/84226, this change adds a volumeattachment lister to verify if a volume is still attached to a node before attempting to delete it. 
Testing:
Deleting a volume that is not attached to a node works as expected:
``` …
```
> Add VolumeAttachment Lister to CSI Provisioner

- .cloudbuild.sh
- Dockerfile
- cloudbuild.yaml
- extras/docker/Dockerfile
- release-tools/SIDECAR_RELEASE_PROCESS.md
- release-tools/build.make
- release-tools/cloudbuild.sh
- release-tools/cloudbuild.yaml
- release-tools/prow.sh
This updates release-tools and then enables cloud image
building in commit 3cedd5d24.
Commit summary for csi-release-tools:
bd416901d cloud build: initial set of shared files
6f2322e80 Update patch release notes generation command
d8c76fee3 Support local snapshot RBAC for pull jobs
ea1f94aad update release tools instructions
7edc1461e Update snapshotter to version 2.0.1
3863a0f67 build for multiple platforms only in CI, add s390x
```release-note
publishing of images on k8s.gcr.io
```
> master: update release-tools, enable cloud build

- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
At present the fstype is set to `ext4` if nothing is passed in storage-class.
However a SP could prefer to have different fstype for many reasons for their
driver/volumes. This patch enables SP who is using the external-provisioner
to choose the  fstype which they want to have it.
Fix# https://github.com/kubernetes-csi/external-provisioner/issues/328
> /kind bug
```release-note
The `defaultFStype` arg is no longer default to "ext4" filesystem type. This arg is available for SP to use when they deploy provisioner sidecar. Admins can also specify this `fstype` via storage class parameter. If `fstype` is set in …
```
> Make fstype configurable in external provisioner

- cmd/csi-provisioner/csi-provisioner.go
Adding configurable throughput for clients to the API server.
Use a separate client for leader election go routine. 
**Testing**
Kubernetes version: 1.17.4
CSI driver: Dummy driver that always returns success for `CreateVolume()` and `DeleteVolume()` callbacks with randomized VolumeID's.
Test: Use 64-threads to create and delete PVCs in a loop for 5 minutes. Tracking the number of operations successfully executed within this time helps calculate the throughput. 
Logs - https://gist.github.com/RaunakShah/ac18639695ff968df84021c1ba12df95
1. QPS = 5.0, Burst = 10 (Default)
a. Number of successful Create and Delete operations - 728
b. Ops/sec - 2.435
I have not pasted the entire log file here but there were 1780 instances of "Throttling ..." within these 5 minutes. 
``` …
```
> Configurable throughput for clients to the API server.

- pkg/controller/controller_test.go
- pkg/controller/topology.go
- pkg/controller/topology_test.go
/kind cleanup
We now require the API server to be on at least 1.17, which means we can remove node support for < 1.15.
Another major change in behavior made here is that if the topology feature gate is enabled, then we assume that the driver on the nodes are correctly reporting topology. We no longer fallback to "no topology" behavior. This means that if you are a driver that is going to upgrade to support topology, then it's a two step process. First, upgrade the driver on the nodes to start reporting topology, then flip the feature gate on the controller.
Fixes #257
```release-note
The topology …
```
> Remove topology fallback logic for nodes < 1.14

- deploy/kubernetes/deployment.yaml
/kind bug
Fixes renamed flag in deployment.yaml
Fixes #454 
```release-note
NONE
```
> Fix wrong flag name in deployment.yaml

- README.md
https://github.com/kubernetes-csi/external-provisioner/pull/447 did not update the README with information about how to use these parameters. Adding a one liner for `--kube-api-qps` and `--kube-api-burst` as part of this PR in the README.
Fixes #
```release-note
Update README with qps and burst argument description
```
> Update README with qps and burst argument description

- pkg/capacity/capacity.go
- pkg/capacity/capacity_test.go
/kind bug
A copy-and-pasted "return" instead of "continue" caused processing to
stop after encountering a storage class with immediate binding, which
had the effect that further CSIStorageCapacity objects for other
storage classes never got created.
This only happened when topology changed at runtime. When topology
was already known when the controller started, all expected objects
got created.
```release-note
CSIStorageCapacity objects were potentially incomplete when at least one storage class used "immediate binding" and topology changed while the controller was already running.
```
> capacity: fix handling of topology changes with immediate binding SCs

- cmd/csi-provisioner/csi-provisioner.go
- deploy/kubernetes/rbac.yaml
- pkg/controller/controller.go
/kind feature
Watching all VolumeAttachments in the cluster even when the CSI driver
itself doesn't support attach/detach causes unnecessary overhead. It
is now automatically enabled if and only if the driver reports the
PUBLISH_UNPUBLISH_VOLUME controller capability.
Checking the capability is better than checking the "skip attach" flag
in the CSIDriver object because the capability is readily available
and constant. It also has the advantage that the watch is disabled for
drivers like csi-host-path-driver which do not support attach/detach
but don't use "skip attach" (for whatever reason).
```release-note
the watch of VolumeAttachements is avoided for drivers which …
```
> optional VolumeAttachments check

- cmd/csi-provisioner/csi-provisioner.go
- deploy/kubernetes/rbac.yaml
- pkg/controller/controller.go
/kind feature
Backport of PR #479 for the release branch.
```release-note
the watch of VolumeAttachements is avoided for drivers which don't support attach/detach (aka controller PUBLISH_UNPUBLISH_VOLUME)
```
> 2.0.x: optional volume attachments

- README.md
Follow up to https://github.com/kubernetes-csi/external-provisioner/pull/457, addressing @pohly's comment - https://github.com/kubernetes-csi/external-provisioner/pull/457#discussion_r464445846
Couldn't find a decent document that describes QPS and Burst explicitly, so just linking to the code documentation. 
Fixes #
```release-note
Adding documentation link to describe QPS and Burst parameters. 
```
> Add link to QPS and Burst documentation

- pkg/features/features.go
/kind feature
This PR is marking topology feature as GA
Fixes https://github.com/kubernetes-csi/external-provisioner/issues/514
```release-note
mark Topology feature gate as GA
```
> mark Topology featuregate as GA

- README.md
- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/topology.go
- pkg/controller/topology_test.go
/kind feature
A CSI driver for local volumes doesn't care about the (long!) list of nodes where the driver is currently running. It needs to track that itself anyway if it supports volume provisioning with immediate binding. The `CreateVolumeRequest` can be made a lot shorter by omitting the topology requirements in that case.
```release-note
TBD
```
> topology: also control for immediate binding

- cmd/csi-provisioner/csi-provisioner.go
- go.mod
- go.sum
- vendor/modules.txt
- vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go
/kind cleanup
sig-storage-lib-external-provisioner used to do one GET of the Node
object when provisioning volumes with a selected node (= late
binding). Scale testing showed that this caused significant traffic
that can easily be avoided by granting the lib access to the shared
informer that external-provisioner has already.
This is also part of PR #524 but can be merged separately.
```release-note
more efficient provisioning of volumes with late binding by avoiding one GET Node per volume
```
> avoid one GET Node per volume with late binding

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind bug
Fix a panic bug caused by unsupported data source.
Fixes #533
None
```release-note
Fix panic when using an external data source
```
> Return an error when data source is unsupported

- README.md
- cmd/csi-provisioner/csi-provisioner.go
- go.mod
- go.sum
- pkg/capacity/capacity_test.go
- pkg/capacity/mode.go
- pkg/capacity/topology/mock.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/ratelimiter.go
- pkg/controller/ratelimiter_test.go
- pkg/controller/topology.go
- vendor/k8s.io/component-helpers/LICENSE
- vendor/k8s.io/component-helpers/scheduling/corev1/doc.go
- vendor/k8s.io/component-helpers/scheduling/corev1/helpers.go
- vendor/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go
- vendor/modules.txt
/kind feature
A CSI driver which manages local resources typically has no control plane and thus (currently) can only provision volumes on a single node. With this PR, external-provisioner gets extended to support deployment alongside a local CSI driver on each node.
The csi-driver-host-path deployment could be extended to use this.
Fixes #487
This is based on https://github.com/kubernetes-csi/external-provisioner/pull/367. Out of courtesy to @jsanda, the original commit is the one from that PR although it gets changed substantially later on. I could also squash more aggressively, if that is desired.
TODO:
**Does this PR introduce a user-facing …
> distributed provisioning

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind bug
Fix the issue where csi provisioner does not honor the volume size returned from CreateVolumeResponse.
Fixes # https://github.com/kubernetes-csi/external-provisioner/issues/199
```release-note
Fix an issue where the csi-provisioner does not honor the volume size returned from CreateVolumeResponse. Stop rounding up bytes returned from CreateVolume.
```
/cc @msau42 
/cc @wongma7
> fix volume size mismatch between driver and PV

- go.mod
- go.sum
- vendor/modules.txt
- vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go
/kind bug
This imports a fix for missing PVC updates in certain scenarios.
```release-note
external-provisioner may have [stopped provisioning](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/103) for a PVC depending on certain timing conditions (provisioning failed once, next attempt currently running, PVC update arrives from API server).
```
> update sig-storage-lib-external-provisioner to v6.3.0

- pkg/capacity/capacity.go
- pkg/capacity/capacity_test.go
/kind bug
Fixes a race.
Fixes #554
This supersedes https://github.com/kubernetes-csi/external-provisioner/pull/559 (squashed commits, test fix, additional comments and logging).
```release-note
producing storage capacity may have failed with `the object has been modified` errors
```
> Capacity informer race

- pkg/capacity/capacity.go
- pkg/capacity/capacity_test.go
/kind bug
Backport of PR #565 
Fixes #554
```release-note
producing storage capacity may have failed with `the object has been modified` errors
```
> Release 2.1: capacity informer race

- pkg/controller/controller.go
- pkg/controller/controller_test.go
> /kind bug
Fixes #552
```release-note
If the in-tree providers are depending on StorageClass for DeleteVolume, volumes could not get deleted after migrating from them. So translate in-tree StorageClass to CSI to get SecretReference in DeleteVolume call for CSI Migration scenario.
```
> Add TranslateInTreeStorageClassToCSI in Delete

- cmd/csi-provisioner/csi-provisioner.go
- go.mod
- pkg/capacity/capacity.go
- pkg/capacity/capacity_test.go
- vendor/github.com/prometheus/client_golang/prometheus/testutil/lint.go
- vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go
- vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
- vendor/k8s.io/component-base/metrics/legacyregistry/registry.go
- vendor/k8s.io/component-base/metrics/prometheus/clientgo/leaderelection/metrics.go
- vendor/k8s.io/component-base/metrics/prometheus/workqueue/metrics.go
- vendor/k8s.io/component-base/metrics/testutil/metrics.go
- vendor/k8s.io/component-base/metrics/testutil/promlint.go
- vendor/k8s.io/component-base/metrics/testutil/testutil.go
- vendor/modules.txt
/kind feature
As pointed out in the KEP review for storage capacity tracking, admins need more insights into the operation of the sidecar than just the CSI calls. This PR adds new metrics gathering specifically for storage capacity tracking, but also enables the gather of metrices that already existed and just weren't reported (process and Go runtime, work queues, leaderelection).
**Note to reviewer**
The commit messages have examples of what the new data looks like. I'm not sure how we want to document this. IMHO we should first decide about central documentation (= https://github.com/kubernetes-csi/docs/issues/339), then add something to each repo as needed. …
> additional metrics

- pkg/capacity/capacity.go
>
> /kind design
> /kind flake
/kind bug
When csi-provisoner start, it will call factory.Start(ctx.Done()). StorageClass Informer and topology Informer is created from factory. It will automatically run when calling factory.Start. Duplication of calling informer.run may cause some problems
Fixes #
```release-note
Redundant CSIStorageCapacity objects might have been created because …
```
> remove duplicate informer.run()

- OWNERS
Adds @chrishenzie to reviewers for this repo.
Originally was going to also add to approvers but going to be added to maintainers instead (required for performing release).
Fixes #
```release-note
NONE
```
> Add chrishenzie to reviewers

- pkg/controller/controller.go
/kind cleanup
These are already logged as part of the gRPC connection.
https://github.com/kubernetes-csi/external-provisioner/pull/601/files#r610842677
Fixes #
```release-note
NONE
```
> Remove redundant log lines

- pkg/capacity/capacity_test.go
/kind cleanup
Sequentially, these tests run slowly (5 minutes). When allowed to run in parallel, they complete in 13 seconds.
The original reason for sequential execution (global registration of
metrics) had already been addressed in an earlier code refactoring
when moving the registration up the call stack, i.e. each test already
had a private registry.
```release-note
NONE
```
> capacity: run tests in parallel

- pkg/capacity/capacity_test.go
/kind failing-test
When introducing parallel testing, it was overlooked that now the "tc"
loop variables get modified before the tests actually run. That caused
random test failures, depending on timing.
Fixes #609 
This bug wasn't in any previous release, therefore this fix doesn't need to be mentioned in the release notes.
```release-note
NONE
```
> capacity test: rebind loop variable to avoid race

- CHANGELOG/CHANGELOG-2.2.md
- README.md
This PR adds the changelog for v2.2.0.
Fixes #
```release-note
NONE
```
> Add changelog for v2.2.0

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind bug
When using immediate binding with allowed topologies set in the storage class together with distributed provisioning, node instances must ignore PVCs that do not fit their node.
Fixes #611 
Includes some drive-by test enhancements.
```release-note
When using immediate binding, allowed topologies and distributed provisioning, PVCs may have been assigned to nodes which did not fit the allowed topologies, leading to permanent `error generating accessibility requirements` failures.
```
/cc @chrishenzie
> distributed provisioning: allowed topologies + immediate binding

- cmd/csi-provisioner/csi-provisioner.go
/kind bug
Don't register `process_start_time_seconds metric` in migration metrics manager to prevent double registration, resulting in this error:
```
gathered metric family process_start_time_seconds has help "[ALPHA] Start time of the process since unix epoch in seconds." but should have "Start time of the process since unix epoch in seconds."
```
This happens only when a migratable CSI driver is used. With a regular hostpath CSI driver, the metrics work without any issues.
Fixes #619
cc @pohly @Jiawei0227 
```release-note
Fixed reporting of metrics when a migratable CSI driver is used.
```
> Fix migration metric registration

- cmd/csi-provisioner/csi-provisioner.go
- pkg/capacity/topology/mock.go
- pkg/capacity/topology/nodes.go
- pkg/capacity/topology/topology.go
/kind bug
bugfix for commit before, if we directly remove topology informer run, the topology worker will not run and do not sync. fix this PR https://github.com/kubernetes-csi/external-provisioner/pull/590
Fixes #
```release-note
Fix capacity information updates when topology changes. Only affected central deployment and network attached storage, not deployment on each node. This broke in v2.2.0 as part of a bug fix for capacity informer handling.
```
> node topology worker should run

- cmd/csi-provisioner/csi-provisioner.go
- pkg/capacity/topology/mock.go
- pkg/capacity/topology/nodes.go
- pkg/capacity/topology/topology.go
/kind bug
Two bug fixes that should go into 2.2.1.
```release-note
- gathered metric family process_start_time_seconds has help "[ALPHA] Start time of the process since unix epoch in seconds." but should have "Start time of the process since unix epoch in seconds."
- Fix capacity information updates when topology changes. Only affected central deployment and network attached storage, not deployment on each node. This broke in v2.2.0 as part of a bug fix for capacity informer handling.
```
> Release 2.2 backport

- CHANGELOG/CHANGELOG-2.2.md
Last step before a v2.2.1 release.
Merging https://github.com/kubernetes-csi/external-provisioner/pull/624 would be useful, but isn't required.
```release-note
NONE
```
> changelog v2.2.1

- release-tools/SIDECAR_RELEASE_PROCESS.md
- release-tools/go-get-kubernetes.sh
- release-tools/prow.sh
- release-tools/pull-test.sh
Squashed 'release-tools/' changes from a1e11275b..6616a6b52
[6616a6b52](https://github.com/kubernetes-csi/csi-release-tools/commit/6616a6b52) Merge [pull request #146](https://github.com/kubernetes-csi/csi-release-tools/pull/146) from pohly/kubernetes-1.21
[510fb0f9c](https://github.com/kubernetes-csi/csi-release-tools/commit/510fb0f9c) prow.sh: support Kubernetes 1.21
[c63c61b3b](https://github.com/kubernetes-csi/csi-release-tools/commit/c63c61b3b) prow.sh: add CSI_PROW_DEPLOYMENT_SUFFIX
[51ac11c3a](https://github.com/kubernetes-csi/csi-release-tools/commit/51ac11c3a) Merge [pull request #144](https://github.com/kubernetes-csi/csi-release-tools/pull/144) from pohly/pull-jobs
[dd54c9269](https://github.com/kubernetes-csi/csi-release-tools/commit/dd54c9269) pull-test.sh: test importing …
> release-2.2: update release-tools

- pkg/capacity/provision.go
/kind bug
Add SupportsBlock method to provisionWrapper for being able to use block device.
Fixes #631
```release-note
Fix a bug that not being able to use block device mode when enable a storage capacity tracking mode.
```
> Add SupportsBlock method to provisionWrapper for being able to use block device

- pkg/capacity/capacity_test.go
/kind flake
This is necessary to ensure that the controller sees all of the
objects when it starts.
The previous approach with Create() was used to ensure that namespace
and UID are set. We now have to take care of that manually.
Fixes #638 
```release-note
NONE
```
> capacity test: create CSIStorageObject before instantiating client-set

- README.md
- cmd/csi-provisioner/csi-provisioner.go
/kind feature
This PR adds command line arguments for leader election options - Lease Duration, Renew Deadline and Retry Period. Currently the defaults are 15, 10 and 5 seconds respectively. Without this change, there's no way for a customer/storage plugin to configure those values. 
This PR makes those parameters configurable. Storage plugins deploying external-provisioner can tune those parameters in their YAMLs accordingly. 
Fixes #556
Testing:
Created Provisioner with new arguments and verified that Pod is running:
```
...
- name: csi-provisioner
args:
- "--v=4"
- "--timeout=300s"
- "--csi-address=$(ADDRESS)"
- "--kube-api-qps=100"
- …
```
> Add command line arguments to configure leader election options

- .prow.sh
/kind cleanup
This PR skips jobs for Kubernetes 1.19 and earlier for external-provisioner repo
to support VolumeSnapshot v1 APIs.
Fixes #
```release-note
NONE
```
> Skip K8S 1.19 jobs

- pkg/controller/clone_controller.go
/kind bug
As mentioned in #590, informers will [automatically start](https://github.com/kubernetes/client-go/blob/v0.21.0/informers/factory.go#L132-L137) when [factory.Start is called](https://github.com/kubernetes-csi/external-provisioner/blob/v2.2.2/cmd/csi-provisioner/csi-provisioner.go#L528). Since calling the extra claimInformer.Run [causes a data race](https://github.com/kubernetes-csi/external-provisioner/issues/595#issuecomment-880420284), it should not be called in CloningProtectionController. I think this PR along with #590 will fix #582.
Fixes #595
https://github.com/kubernetes-csi/external-provisioner/issues/595#issuecomment-879678124 is …
> Fix data race in cloning protection controller

- README.md
- cmd/csi-provisioner/csi-provisioner.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
Refer: https://github.com/kubernetes/kubernetes/issues/70505
```release-note
The provisioner sidecar now has an argument called `controller-publish-readonly`
which set the value of CSI PV spec `readonly` field value based on the PVC access mode. 
If this flag has been set to `true` and pvc access mode carry only `ROX` access mode,
the controller automatically set PersistentVolume.spec.CSIPersistentVolumeSource.readOnly
field  to `true`.
```
> Set READONLY flag in CSI PV based on PVC accessmode

- pkg/controller/controller.go
/kind cleanup
All occurrences reported by the unused linter of golangci-lint.
```release-note
NONE
```
> Clean up unused vars and types

- pkg/controller/clone_controller.go
/kind bug
cherry-pick https://github.com/kubernetes-csi/external-provisioner/pull/651 to v2.
Fixes https://github.com/kubernetes-csi/external-provisioner/issues/595
```release-note
cherry-pick #651: Fix a data race in cloning protection controller
```
> Fix data race in cloning protection controller (v2.2)

- release-tools/README.md
- release-tools/SECURITY_CONTACTS
- release-tools/SIDECAR_RELEASE_PROCESS.md
- release-tools/build.make
- release-tools/cloudbuild.yaml
- release-tools/go-get-kubernetes.sh
- release-tools/prow.sh
Squashed 'release-tools/' changes from c0a4fb1dd..a6a1a7979
[a6a1a7979](https://github.com/kubernetes-csi/csi-release-tools/commit/a6a1a7979) Merge [pull request #176](https://github.com/kubernetes-csi/csi-release-tools/pull/176) from pohly/go-1.17.3
[0a2cf636c](https://github.com/kubernetes-csi/csi-release-tools/commit/0a2cf636c) prow.sh: bump Go to 1.17.3
[fc29fdde5](https://github.com/kubernetes-csi/csi-release-tools/commit/fc29fdde5) Merge [pull request #141](https://github.com/kubernetes-csi/csi-release-tools/pull/141) from pohly/prune-replace-optional
[5b9a1e067](https://github.com/kubernetes-csi/csi-release-tools/commit/5b9a1e067) Merge [pull request #175](https://github.com/kubernetes-csi/csi-release-tools/pull/175) from jimdaga/patch-1 …
> release-3.0: update release-tools

- cmd/csi-provisioner/csi-provisioner.go
- pkg/capacity/capacity.go
- pkg/capacity/capacity_test.go
/kind bug
bug
If one node csidriver fails or it does not set any timeout for grpc, this sync capacity will stuck here. If we only use one thread to process CSIStoragecapacities, it will stuck forever. Provisioning pv or delete all has timeout, it should have timeout for GetCapacity as well
Fixes #
```release-note
Add getCapacity request timeout to avoid hang forever
```
> bugfix: get capacity grpc request should have timeout

- .gitignore
- README.md
- cmd/csi-provisioner/csi-provisioner.go
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
/kind feature
- Adds an option to enable pprof profiling
Fixes #
```release-note
Added an option to enable pprof profiling with --enable-pprof. The profiling server port can be configured using --http-endpoint.
```
> feat: add an option to enable pprof profiling

- pkg/controller/controller.go
- pkg/controller/controller_test.go
The restriction that cloning is only supported within the same Storage Class, restricts PVC cloning in some cases. For example, if you want to clone from a zonal volume --> regional volume, the replication-type for these two volumes must be different, so they require different Storage Classes. Currently snapshot allows for restoring from a snapshot with a different StorageClass, and it leaves the validation up to the CSI Drivers. No validation is done in the external provisioner to make sure the Storage Classes are compatible. For PVC cloning, validation will also be up to the CSI Drivers.
Fixes https://github.com/kubernetes-csi/docs/issues/490
**Does this PR introduce a …
> relax same storageclass restriction

- cmd/csi-provisioner/csi-provisioner.go
/kind feature
The rationale behind this change is that it allows external-provisioner to deal
with volumes without being slowed down by the concurrent CSIStorageCapacity
updates. Those updates are less important and the scheduler can deal with
outdated information, so enforcing a lower rate by default is acceptable.
If few changes are needed, updating CSIStorageCapacity keeps up with volume
changes. If many volumes get created or deleted quickly, throttling the
updating is beneficial because multiple changes can be combined into a single
update.
This has helped in practice during a scale test with 100 nodes and 10000
pods+volumes. Without this change, there were intermittent problems with an
unresponsive apiserver. With …
> capacity: use separate client and lower QPS/Burst settings

- pkg/controller/controller.go
- pkg/controller/controller_test.go
Fixes #330 
-->
```release-note
Previous to this release, if the SC does not exist at time of PVC deletion where provisioner need credentials to delete volume which was passed as SC parameter at creation time, the PV deletion will fail as it can not fetch credentials by reading the SC from the API server. However this workflow is improved from this release which allows the PV deletion to succeed even if SC was deleted or does not exist at time of PV deletion. 
```
> controller: add pv secret annotation support to forget SC

- cmd/csi-provisioner/csi-provisioner.go
- cmd/csi-provisioner/util.go
- cmd/csi-provisioner/util_test.go
Added a hashing function that only hashes the passed in base and
prefix if the combined size is > the maxLength passed into the function
In this case the maximum length of a label.
Signed-off-by: Alexander Wels <awels@redhat.com>
>
/kind bug
> /kind design
> /kind flake
Fixes #707 
```release-note
storage capacity: managed-by label potentially too long with a long node name and …
```
> fix managed-by label being too long when the node name is long.

- deploy/kubernetes/rbac.yaml
Considering we have removed leader election based on endpoints.
-->
```release-note
NONE
```
> rbac: remove unwaned rbac for the leader election

- README.md
- cmd/csi-provisioner/csi-provisioner.go
- go.mod
- go.sum
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- vendor/modules.txt
/kind feature
KEP - https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3141-prevent-volume-mode-conversion#changes-to-external-provisioner
**Testing**
Setup: 
- Enable feature `prevent-volume-mode-conversion` on `external-provisioner` and `external-snapshotter` 
- create VolumeSnapshot APIs from `release-6.0` branch.
- Create PVC and VolumeSnapshot of the PVC. Identify the VolumeSnapshotContent corresponding to that VolumeSnapshot.
1. Create a new PVC from Snapshot with annotation `snapshot.storage.kubernetes.io/allowVolumeModeChange: true` on snapshotcontent and attempt to convert volume mode.
PVC creation succeeds:
```
% kubectl get volumesnapshotcontent -o yaml …
```
> Provisioner changes to prevent unauthorised volume mode conversion

- cmd/csi-provisioner/csi-provisioner.go
/kind bug
bug
If a user deploys a csi external-provisioner multi-replicas pod and the pod network is hostNetwork, when there are multiple external-provisioner pods running on a node, these pods will be the leaders. Because the default identity is hostname, and the hostname of the hostNetwork pod is the same as the hostname of the node. This requires adding a unique identifier for the provisioner leader.
```
func (l *leaderElection) Run() error {
if l.identity == "" {
id, err := defaultLeaderElectionIdentity()       ##NOTE: will return os.Hostname()
if err != nil {
return fmt.Errorf("error getting the default leader identity: %v", err)
}
l.identity = id
}
```
Fixes #
**Does this …
> bugfix:  add unique identity to the leaderrelection leader.

- cmd/csi-provisioner/csi-provisioner.go
- cmd/csi-provisioner/util.go
- cmd/csi-provisioner/util_test.go
Signed-off-by: Alexander Wels <awels@redhat.com>
/kind bug
Cherry-pick of #717 for the release-3.1 branch, as discussed in https://github.com/kubernetes-csi/external-provisioner/pull/717#issuecomment-1126920943.
Fixes #707
```release-note
storage capacity: managed-by label potentially too long with a long node name and enableNodeDeployment set to true
```
> [release-3.1] backport 'fix managed-by label being too long when the node name is long.'

- pkg/controller/controller.go
/kind bug
The DeleteFunc callback may get called with a cache.DeletedFinalStateUnknown
object. This needs to be handled as in
https://github.com/kubernetes-csi/external-attacher/blob/v3.2.1/pkg/controller/controller.go#L171-L173
Fixes #628
```release-note
Certain informer delete events were not handled correctly.
```
> controller: handle cache.DeletedFinalStateUnknown

- CHANGELOG/CHANGELOG-3.2.md
/kind cleanup
```release-note
NONE
```
> v3.2.0 CHANGELOG

- cmd/csi-provisioner/csi-provisioner.go
Cherry pick of #690 on release-3.1.
#690: add unique identity to the leaderrelection leader.
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
```
> Automated cherry pick of #690: add unique identity to the leaderrelection leader.

- pkg/controller/controller.go
Cherry pick of #745 on release-3.1.
#745: controller: handle cache.DeletedFinalStateUnknown
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
```
> Automated cherry pick of #745: controller: handle cache.DeletedFinalStateUnknown

- CHANGELOG/CHANGELOG-3.1.md
> v3.1.1 CHANGELOG

- cmd/csi-provisioner/csi-provisioner.go
The CSIStorageCapacity v1 check was attempting to create an invalid
object in the default namespace. This would fail if the pod did not
have permissions to the namespace. This will now use the namespace
specified in the NAMESPACE env variable.
Signed-off-by: N Balachandran <nibalach@redhat.com>
/kind bug
The CSIStorageCapacity version check attempts to create an invalid resource in the default namespace. If the pod does not have permissions on "default" , this check returns with a fatal error.
Fixes #752 
```release-note
The CSIStorageCapacity version check will now use the namespace specified in the …
```
> fix: changed the csistoragecapacity check namespace

- cmd/csi-provisioner/csi-provisioner.go
Cherry pick of #753 on release-3.2.
#753: fix: changed the csistoragecapacity check namespace
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
```
> Automated cherry pick of #753: fix: changed the csistoragecapacity check namespace

- README.md
- doc/design.md
Because of Kubernetes proposal design proposals have been archived, the
relevant link in the current document is no longer working. So I made an
update with this commit.
Signed-off-by: LetFu <letfu@outlook.com>
Kubernetes design proposal URL expired, the link in the current document is no longer working.
```release-note
Updated README and design documentation
```
> fix: kubernetes design proposal URL expired

- release-tools/KUBERNETES_CSI_OWNERS_ALIASES
- release-tools/SIDECAR_RELEASE_PROCESS.md
- release-tools/build.make
- release-tools/cloudbuild.yaml
- release-tools/filter-junit.go
- release-tools/go-get-kubernetes.sh
- release-tools/prow.sh
- release-tools/verify-spelling.sh
Squashed 'release-tools/' changes from a6a1a7979..d29a2e754
[d29a2e754](https://github.com/kubernetes-csi/csi-release-tools/commit/d29a2e754) Merge [pull request #198](https://github.com/kubernetes-csi/csi-release-tools/pull/198) from pohly/csi-test-5.0.0
[41cb70d38](https://github.com/kubernetes-csi/csi-release-tools/commit/41cb70d38) prow.sh: sanity testing with csi-test v5.0.0
[c85a63fbf](https://github.com/kubernetes-csi/csi-release-tools/commit/c85a63fbf) Merge [pull request #197](https://github.com/kubernetes-csi/csi-release-tools/pull/197) from pohly/fix-alpha-testing
[b86d8e942](https://github.com/kubernetes-csi/csi-release-tools/commit/b86d8e942) support Kubernetes 1.25 + Ginkgo v2
[ab0b0a3d4](https://github.com/kubernetes-csi/csi-release-tools/commit/ab0b0a3d4) Merge [pull …
> release-3.1: update release-tools

- .github/dependabot.yaml
/kind cleanup
After the trial in csi-test and csi-driver-iscsi we want to role out the same automatic dependency update also in other repos.
```release-note
NONE
```
> github: enable dependabot

- pkg/controller/controller.go
- pkg/controller/controller_test.go
/kind feature
Support secret in NodeExpansion Call
Fixes #499 
```release-note
This release add the support for  CSINodeExpandSecret feature (https://github.com/kubernetes/enhancements/issues/3107). The CSI drivers can make use of the secret as part of the nodeExpandVolume RPC call from now onwards.
```
> feat: Support secret in NodeExpansion Call

- cmd/csi-provisioner/csi-provisioner.go
/kind feature
This PR registers metrics exposed by sig-storage-lib in the external provisioner. 
After this change, querying the http endpoint includes the following metrics:
1. Create an nginx pod in the cluster
2. Get the IP address of the Pod running csi-provisioner
```
% kubectl get pod -o wide
NAME                   READY   STATUS    RESTARTS   AGE     IP            NODE              NOMINATED NODE   READINESS GATES
csi-hostpath-socat-0   1/1     Running   0          31h     10.244.1.6    csi-prow-worker   <none>           <none>
csi-hostpathplugin-0   8/8     Running   0          5h47m   10.244.1.23   csi-prow-worker   <none>           <none>
nginx                  1/1     Running   0          9h      10.244.1.18 …
```
> Register metrics exposed by sig-storage-lib

- pkg/controller/controller.go
/kind feature
This PR updates the annotation that needs to be applies to `VolumeSnapshotContents` from `snapshot.storage.kubernetes.io/allowVolumeModeChange` to `snapshot.storage.kubernetes.io/allow-volume-mode-change`. 
The feature is still in the Alpha stage. 
Fixes #
```release-note
Update the annotation that needs to be applies to VolumeSnapshotContents from snapshot.storage.kubernetes.io/allowVolumeModeChange to snapshot.storage.kubernetes.io/allow-volume-mode-change
```
> Change annotation name to allow volume mode change

- pkg/controller/controller.go
/kind bug
This PR fixes a bug where string addresses were being compared for equality instead of the actual string values. 
Due to this bug, even if the source volume mode is unchanged, the VolumeSnapshotContent object needed the `allowVolumeModeChange` annotation to be set to true for PVC creation to succeed. 
Fixes #
```release-note
Fix string pointer comparison for source volume mode conversion
```
> Fix string pointer comparison for source volume mode conversion

- release-tools/KUBERNETES_CSI_OWNERS_ALIASES
- release-tools/prow.sh
Squashed 'release-tools/' changes from d24254f6a..78c0fb714
[78c0fb714](https://github.com/kubernetes-csi/csi-release-tools/commit/78c0fb714) Merge [pull request #208](https://github.com/kubernetes-csi/csi-release-tools/pull/208) from jsafrane/skip-selinux
[36e433e2a](https://github.com/kubernetes-csi/csi-release-tools/commit/36e433e2a) Skip SELinux tests in CI by default
[348d4a92f](https://github.com/kubernetes-csi/csi-release-tools/commit/348d4a92f) Merge [pull request #207](https://github.com/kubernetes-csi/csi-release-tools/pull/207) from RaunakShah/reviewers
[1efc27241](https://github.com/kubernetes-csi/csi-release-tools/commit/1efc27241) Merge [pull request #206](https://github.com/kubernetes-csi/csi-release-tools/pull/206) from RaunakShah/update-prow …
> release-3.3: update release-tools

- pkg/controller/controller.go
- pkg/controller/topology.go
- release-tools/KUBERNETES_CSI_OWNERS_ALIASES
- release-tools/filter-junit.go
- release-tools/go-get-kubernetes.sh
- release-tools/prow.sh
Squashed 'release-tools/' changes from e4dab7ff5..78c0fb714
[78c0fb714](https://github.com/kubernetes-csi/csi-release-tools/commit/78c0fb714) Merge [pull request #208](https://github.com/kubernetes-csi/csi-release-tools/pull/208) from jsafrane/skip-selinux
[36e433e2a](https://github.com/kubernetes-csi/csi-release-tools/commit/36e433e2a) Skip SELinux tests in CI by default
[348d4a92f](https://github.com/kubernetes-csi/csi-release-tools/commit/348d4a92f) Merge [pull request #207](https://github.com/kubernetes-csi/csi-release-tools/pull/207) from RaunakShah/reviewers
[1efc27241](https://github.com/kubernetes-csi/csi-release-tools/commit/1efc27241) Merge [pull request #206](https://github.com/kubernetes-csi/csi-release-tools/pull/206) from RaunakShah/update-prow …
> release-3.2: update release-tools

- CHANGELOG/CHANGELOG-3.4.md
- README.md
Adds changelog for upcoming `v3.4.0` release. 
Fixes #
```release-note
NONE
```
> Add changelog for v3.4.0

- test/e2e/storage/provision.go
/kind test
Follow up to https://github.com/kubernetes-csi/external-provisioner/pull/832
This adds further e2e tests described in the feature KEP - https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3141-prevent-volume-mode-conversion#e2e-tests
Test output:
```
provision volumes with different volume modes from volume snapshot dataSource when the source volume mode is altered with permissions
/Users/raunakshah/go/src/github.com/kubernetes-csi/external-provisioner/test/e2e/storage/provision.go:154
STEP: Creating a kubernetes client @ 02/07/23 14:18:59.983
Feb  7 14:18:59.983: INFO: >>> kubeConfig: /Users/raunakshah/.kube/config
STEP: Building a namespace api object, basename pvcs-from-volume-snapshots …
```
> Add tests for volume mode conversion feature

- go.mod
- go.sum
- vendor/modules.txt
- vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go
/kind bug
Fixes #https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/121
```release-note
Fix stuck pod scheduled to a non exist node
```
> Update sig-storage-lib-external-provisioner to v8.0.1

- README.md
Fixes #
```release-note
NONE
```
> Update feature status for 1.27

- pkg/controller/controller.go
unnecessary use of fmt.Sprintf
the argument's underlying type is a string, should use a simple conversion instead of fmt.Sprintf
Fixes #
```release-note
NONE
```
> chore: unnecessary use of fmt.Sprintf

- release-tools/SIDECAR_RELEASE_PROCESS.md
- release-tools/cloudbuild.yaml
- release-tools/contrib/get_supported_version_csi-sidecar.py
- release-tools/prow.sh
63473cc96 Merge pull request #231 from coulof/bump-go-version-1.20.5
29a5c76c7 Merge pull request #228 from mowangdk/chore/adopt_kubernetes_recommand_labels
8dd28211b Update cloudbuild image with go 1.20.5
1df23dba6 Merge pull request #230 from msau42/prow
1f92b7e7c Add ginkgo timeout to e2e tests to help catch any stuck tests
c10b67804 Merge pull request #227 from coulof/check-sidecar-supported-versions
72984ec0a chore: adopt kubernetes recommand label
b05553510 Header
bd0a10b65 typo
c39d73c33 Add comments
f6491af0e Script to verify EOL sidecar version
-->
```release-note
NONE
```
> Release tools update

- .github/dependabot.yaml
/kind cleanup
Let dependabot update all dependencies, not only the direct ones. For example, golang.org/x/net should be updated because it had a recent CVE.
This is an experiment, we'll see what it does in external-provisioner before applying it to all other repos.
Fixes #
```release-note
NONE
```
> Enable dependabot for all dependencies

- .github/dependabot.yaml
/kind cleanup
Group the rest of dependencies so it does not open a single dependency update similar to this PR https://github.com/kubernetes-csi/external-provisioner/pull/1007
Fixes #
```release-note
NONE
```
> Group the rest of dependencies in dependabot

- pkg/controller/controller_test.go
"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16
Fixes #
```release-note
NONE
```
> chore: remove refs to deprecated io/ioutil

- .github/dependabot.yaml
/kind cleanup
Add back groups and we can use [dependabot command like ignore](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#managing-dependabot-pull-requests-for-grouped-version-updates-with-comment-commands) to exclude packages.
Fixes #
```release-note
NONE
```
> Add Back Groups for Github Dependencies

- release-tools/SIDECAR_RELEASE_PROCESS.md
- release-tools/generate_patch_release_notes.sh
- release-tools/prow.sh
- release-tools/pull-test.sh
/kind cleanup
Squashed 'release-tools/' changes from f9d5b9c05..f8c8cc4c7
f8c8cc4c7 Merge pull request https://github.com/kubernetes-csi/external-provisioner/pull/237 from msau42/prow
b36b5bfdc Merge pull request https://github.com/kubernetes-csi/external-provisioner/pull/240 from dannawang0221/upgrade-go-version
adfddcc9a Merge pull request https://github.com/kubernetes-csi/external-provisioner/pull/243 from pohly/git-subtree-pull-fix
c4650889d pull-test.sh: avoid "git subtree pull" error
7b175a1e2 Update csi-test version to v5.2.0
987c90ccd Update go version to 1.21 to match k/k
2c625d41d Add script to generate patch release notes
git-subtree-dir: release-tools
git-subtree-split: …
> Update release tools

- README.md
- cmd/csi-provisioner/csi-provisioner.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This is beta since 1.27 so we can safely default to true, to get this new validation logic. https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/3141-prevent-volume-mode-conversion/kep.yaml#L30
Fixes #
```release-note
Enable prevent-volume-mode-conversion feature flag by default.
ACTION REQUIRED: 
Volume mode change will be …
```
> Enable prevent-volume-mode-conversion by default following k8s 1.28 release

- go.mod
- go.sum
- vendor/golang.org/x/crypto/ssh/channel.go
- vendor/golang.org/x/crypto/ssh/client.go
- vendor/golang.org/x/crypto/ssh/handshake.go
- vendor/golang.org/x/crypto/ssh/server.go
- vendor/golang.org/x/crypto/ssh/transport.go
- vendor/modules.txt
What type of PR is this?
/kind bug
What this PR does / why we need it:
fix: [CVE-2023-48795](https://github.com/advisories/GHSA-45x7-px36-x8w8)
Release note:
```release-note
fix: CVE-2023-48795
```
> CVE-2023-48795: bump golang.org/x/crypto to v0.17.0

- release-tools/prow.sh
/kind cleanup
Squashed 'release-tools/' changes from b54c1ba49..dc4d0ae20
dc4d0ae20 Merge pull request https://github.com/kubernetes-csi/external-provisioner/pull/249 from jsafrane/use-go-version
e681b170e Use .go-version to get Kubernetes go version
git-subtree-dir: release-tools
git-subtree-split: dc4d0ae20a3dcce17fbfc745fb1f1e3b10cd9644
Fixes #
```release-note
NONE
```
> Update release tools - go version

- release-tools/prow.sh
>
/kind cleanup
Squashed 'release-tools/' changes from de2fba88..dc4d0ae2
```
git subtree pull --squash --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master
```
Fixes #
```release-note
N/A
```
> [release-4.0] Update release tools with go version fix

- pkg/controller/clone_controller.go
- pkg/controller/controller.go
/kind bug
If the cloner controller directly updates the PVC reference without using a deep copy and then calls the Update() method, it can lead to a situation where the cached PVC is updated (removing the finalizer), while the actual PVC remains unmodified in case the Update() operation fails.
Fixes #1188 
```release-note
Fix clone controller shallow copy bug
```
> Fix clone controller shallow copy bug

- pkg/capacity/capacity.go
/kind bug
`external-provisioner` calls `GetCapacity()` with "faked" VolumeCapabilities, but it is confusing for CSI driver implementations to validate the capabilities. For example, the access mode is always `VolumeCapability_AccessMode_UNKNOWN`, but it's unclear for an implementation how to handle an "UNKNOWN" mode. And the access type is always `mount`, it also confuses block-oriented CSI drivers.
The comment says "The standard makes it mandatory to pass something, therefore we pick something rather arbitrarily.", but according to the latest CSI spec, the field is optional. So I think we can simply set an empty value to that field.
https://github.com/container-storage-interface/spec/blob/2696773158b970c65107610d8f3ef430 …
> fix: don't pass confusing value to GetCapacityRequest.VolumeCapabilities

- pkg/controller/controller.go
- pkg/controller/controller_test.go
Provisioner can resolve templated per volume secret in storage class such as following example: `csi.storage.k8s.io/provisioner-secret-name: ${pvc.annotations['example.com/foo_secret']} `
The secret will be stored as metadata in annotations of PV, so it can find the secret OnDelete even the PVC was deleted
/kind feature
Inconsistent usage of per volume secrets in storage class with parameter like `csi.storage.k8s.io/provisioner-secret-name`
We can support syntax like other API does
`csi.storage.k8s.io/node-publish-secret-name: ${pvc.annotations['team.example.com/key']}`
Fixes #1148
We can use original PVC object to resolve secret during provision and …
> feat: support PVC annotation template for provisioner secret

- deploy/kubernetes/rbac.yaml
/kind bug
the feature-gate HonorPVReclaimPolicy is enabled, create a pvc with a delete relaim policy, then delete the pvc, the pv stuck in deleting status, the error message is:
```
csi-mockplugin-0/csi-provisioner@kind..lane: I0206 11:08:41.536819       1 controller.go:1523] delete "pvc-e4b6e20e-4d77-4bf0-8d96-9f47212e4b38": failed to remove finalizer for persistentvolume: persistentvolumes "pvc-e4b6e20e-4d77-4bf0-8d96-9f47212e4b38" is forbidden: User "system:serviceaccount:csi-mock-honor-pv-reclaim-policy-99-996:csi-mock" cannot update resource "persistentvolumes" in API group "" at the cluster scope: RBAC: [clusterrole.rbac.authorization.k8s.io "cluster-driver-registrar-runner-csi-mock-honor-pv-reclaim-policy-99" not …
```
> add patch verb for persistentvolumes resources in the external-provisioner-runner clusterrole

- pkg/features/features.go
/kind cleanup
>
> /kind bug
> /kind design
> /kind flake
This feature gate has already existed for 5 years. And should be safe to enable by default.
Besides, because this feature gate has been marked as GA, it will show warnings: `Setting GA feature gate Topology=true. It will be removed in a future release.`. So I went ahead and removed this feature gate from command line. Then something breaks, which is very confusing. I would expect a GA feature gate to default to true. …
> set Topology feature gate default to true

- README.md
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/features/features.go
>
> /kind bug
> /kind design
> /kind flake
Promote VolumeAttributesClass feature gate to Beta to match [promotion of upstream KEP #3751](https://github.com/kubernetes/enhancements/issues/3751) in Kubernetes v1.31.
Fixes #
```release-note
Promote VolumeAttributesClass feature gate to beta. If VolumeAttributesClass feature gate gate is enabled, this sidecar may only be used with Kubernetes …
```
> Promote VolumeAttributesClass to Beta

- CHANGELOG/CHANGELOG-5.1.md
- README.md
>
> /kind bug
> /kind design
> /kind flake
Add changelog for v5.1.0
Fixes #
Unsure if waiting for #1262, I can edit my commits if we merge that. @jsafrane feel free to unhold this PR if we are not waiting. 
/hold 
Canaries seem to be passing: https://testgrid.k8s.io/sig-storage-csi-ci
Push-image tests passing: https://testgrid.k8s.io/sig-storage-image-build#canary-external-provisioner-push-images
**Does this PR introduce a user-facing …
> Add changelog for v5.1.0

- pkg/capacity/capacity_test.go
/kind bug
When running tests with `-race` go routine leaks on `capacityCounter` & `utilruntime.ReallyCrash`
Creating mutex for these variables fixes it.
```release-note
NONE
```
> fix data race on makeCapacity & fakeController

- cmd/csi-provisioner/csi-provisioner.go
/kind feature
If not specified explicitly, JSON encoding is used by default when talking to kube-apiserver.
For core K8s API objects like Pods, Nodes, etc., we can use protobuf encoding which reduces CPU consumption related to (de)serialization, reduces overall latency of the API call, reduces memory footprint, reduces the amount of work performed by the GC and results in quicker propagation of objects to event handlers of shared informers.
For CRDs, however, we still have to stick to JSON since they do not support protobuf encoding.
No issue is opened for that.
Standard system components of K8s default their serialization method to protobuf for some …
> Use protobuf encoding for core K8s APIs in external-provisioner

- pkg/controller/topology.go
- pkg/controller/topology_test.go
/kind cleanup
Greatly reduce the CPU and memory usage, especially for drivers assign different topology to each host. Benchmark shows 30x CPU reduction and 21x memory allocation size reduction.
We were performing a stress test recently, and found the bottleneck to be the CPU usage of external-provisioner. From profiling, `topologyTerm.hash` takes almost all the CPU time (apart from logGRPC).
Our setup is a 3k node cluster, each node has a distinct topology. It took about 50s for provisioning 3k immediate binding volumes, despite that we have raised the CPU limit to 10. external-provisioner also took ~3GiB memory, which is far higher than expected.
[This](https://github.com/huww98/external-provisioner/commit/4998f1d35d2f70 …
> Optimize for topology term

- release-tools/prow.sh
/kind cleanup
Squashed 'release-tools/' changes from 049659326..0a435bf98
0a435bf98 Merge pull request https://github.com/kubernetes-csi/external-provisioner/pull/274 from andyzhangx/patch-5
cd7b4bba3 Bump golang to 1.24.2 to fix https://github.com/advisories/GHSA-g9pc-8g42-g6vq
701dc34bc Merge pull request https://github.com/kubernetes-csi/external-provisioner/pull/273 from andyzhangx/patch-4
aeebd30e8 Bump golang to 1.24.0
f277d561f Merge pull request https://github.com/kubernetes-csi/external-provisioner/pull/270 from carlory/update-kind-version
90efb2ca5 Merge pull request https://github.com/kubernetes-csi/external-provisioner/pull/272 from andyzhangx/patch-3
9b616fec4 Bump golang to 1.23.6 to fix https://github.com/advisories/GHSA-7wrw-r4p8-38rx, …
> External provisioner csi tool update
