kubernetes-csi/external-provisioner

pkg/controller/controller.go

Closes #13
Signed-off-by: Luis Pabón <luis@portworx.com>

StorageClass parameters to CSI CreateVolume call

---

pkg/controller/controller.go

Credentials are not sent in DeleteVolume call (#53)

---

.travis.yml
Gopkg.lock
Gopkg.toml
pkg/controller/controller_test.go

Adding unit test to external provisioner

Adding unit tests to external provisioner

---

pkg/controller/controller.go

fix https://github.com/kubernetes-csi/external-provisioner/issues/55
/assign @jsafrane

Errors from fetching secrets should be reported

---

README.md

This PR aligns the actual code with the described one in README.md file
Signed-off-by: Dennis Chen <dennis.chen@arm.com>

Fix mismatch between the codes and README.md

---

pkg/controller/controller.go

Fixes issue#72

---

pkg/controller/controller.go
pkg/controller/controller_test.go

Made storage shown in PV more readable

---

pkg/controller/controller.go

Allow fsType parameter from StorageClass

---

pkg/controller/controller.go
pkg/controller/controller_test.go

Copy the mount options from the storage class to the PV spec and pass mount option to the CSI driver when creating volumes.
Fixes #125

Support mount options

---

pkg/controller/controller_test.go

Fix formatting issue

---

pkg/controller/controller.go

Remove redundant else block

---

README.md

markdown linter corrections in README

---

pkg/controller/controller.go
pkg/controller/controller_test.go

Correct variable declaration.

---

Gopkg.lock
Gopkg.toml
vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go
vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/volume.go

update kubernetes-sigs/sig-storage-lib-external-provisioner to fix #195

---

pkg/controller/controller.go

Remove unused logGRPC

---

CHANGELOG-1.2.md

Add a changelog for v1.2 release
/assign @msau42 
```release-note
NONE
```

Add 1.2 changelog

---

Gopkg.lock
vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
vendor/k8s.io/csi-translation-lib/translate.go

/kind cleanup
/kind feature
/assign @msau42 @jsafrane 
/cc @leakingtapan @ddebroy
```release-note
Adds CSI Migration support for Azure Disk/File, adds some backwards compatibility fixes for GCE PD Migration
```

Bump version of csi-translation-lib for CSI Migration support for Azure Disk/File, as well as backwards compatibility fixes for GCE PD

---

Gopkg.lock
vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
vendor/k8s.io/csi-translation-lib/translate.go

/kind cleanup
/kind feature
/assign @msau42 @jsafrane 
/cc @leakingtapan @ddebroy
```release-note
Adds CSI Migration support for Azure Disk/File, adds some backwards compatibility fixes for GCE PD Migration
```

[cherry-pick] Bump version of csi-translation-lib for CSI Migration support for Azure Disk/File, as well as fixes for GCE PD

---

CHANGELOG-1.2.md

Fixes #
```release-note
NONE
```

Update 1.2 changelog

---

CHANGELOG-1.2.md

Cherry pick of #279, #293, and #299
Fixes #
```release-note
NONE
```

Cherry-pick 1.2 changelog to release-1.2

---

README.md

Fixes #
```release-note
NONE
```

update readme with --leader-election-namespace flag

---

README.md

Fixes #
```release-note
NONE
```

Cherry-pick #302 to release-1.2: update readme with --leader-election-namespace flag

---

README.md

Fixes #
```release-note
NONE
```

Cherry-pick #302 to release-1.1: update readme with --leader-election-namespace flag

---

pkg/features/features.go

/kind cleanup
Fix feature gate comment to reflect that topology went beta in 1.2 version of the provisioner
Fixes #
```release-note
NONE
```

fix topology beta version

---

cmd/csi-provisioner/csi-provisioner.go

/kind bug
Fix typo for leader-election-type
Fixes #
```release-note
```

Fix typo for leader-election-type

---

Gopkg.lock
Gopkg.toml
vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go
vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/volume_store.go

/kind api-change
Update to v4.0.1 to fix logging issues.
Fixes #321
```release-note
Reduced logging noise of unrelated PVCs.
Emit event on successful provisioning.
```

Update sig-storage-lib-external-provisioner to v4.0.1

---

CHANGELOG-1.4.md
README.md

Fixes #
```release-note
NONE
```

Update 1.4 documentation

---

release-tools/README.md
release-tools/build.make
release-tools/go-get-kubernetes.sh
release-tools/prow.sh
release-tools/travis.yml

/kind cleanup
Fixes #
```release-note
NONE
```

Update prow to latest release-tools

---

release-tools/README.md
release-tools/build.make
release-tools/go-get-kubernetes.sh
release-tools/prow.sh
release-tools/travis.yml

/kind cleanup
Fixes #
```release-note
NONE
```

Update prow 1.2

---

CHANGELOG-1.2.md

Fixes #
```release-note
NONE
```

Update changelog for v1.2.2

---

release-tools/README.md
release-tools/build.make
release-tools/go-get-kubernetes.sh
release-tools/prow.sh
release-tools/travis.yml

/kind cleanup
Fixes #
```release-note
NONE
```

Update prow 1.3

---

CHANGELOG-1.0.md

We didn't have a changelog file for 1.0.x, so adding a new file and also included older v1.0.1 changelog history as well using the old format.
Fixes #
```release-note
NONE
```

Add 1.0 changelog for v1.0.2

---

CHANGELOG-0.4.md

Fixes #
```release-note
NONE
```

Add changelog for v0.4.3

---

pkg/controller/topology_test.go

/kind cleanup
/kind failing-test
Fixes #
```release-note
NONE
```

fix wrong compare expression in testcase in pkg controller

---

CHANGELOG-1.5.md
README.md

Fixes #
```release-note
NONE
```

Add changelog for 1.5

---

CHANGELOG-1.5.md

Fixes #
```release-note
NONE
```

fix typo in changelog

---

README.md
cmd/csi-provisioner/csi-provisioner.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fix typos in metrics docs
Fixes #
```release-note
NONE
```

Fix metrics typos

---

cmd/csi-provisioner/csi-provisioner.go

/kind bug
This PR fixes a nil pointer dereference due to the storageClass lister being initialized in the wrong place (i.e., only when topology was supported). This bug was introduced in https://github.com/kubernetes-csi/external-provisioner/commit/0c73acbb0b576c42319dc06692da61cd68ba9b75.
I tested this fix with csi-hostpath driver.
Fixes #395
```release-note
NONE
```

Fix initialization of storageClass lister

---

README.md
pkg/controller/controller.go

Avoid explicit initialization of err var

---

CHANGELOG-1.6.md
README.md

prepare for 1.6 release
Fixes #
```release-note
NONE
```

Add documentation for 1.6

---

CHANGELOG-1.6.md

Fixes #
```release-note
NONE
```

fix changelog formatting

---

pkg/controller/clone_controller_test.go
pkg/controller/controller.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```

Correct package import and var declaration

---

CHANGELOG-1.1.md
CHANGELOG-1.2.md
CHANGELOG-1.3.md
CHANGELOG-1.4.md
CHANGELOG-1.5.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```

md linter fixes

---

CHANGELOG/CHANGELOG-2.0.md

Update changelog to pick up new prs
Fixes #
```release-note
NONE
```

Update 2.0 changelog

---

README.md

1.19 is recommended for the capacity reporting alpha feature
Fixes #
```release-note
NONE
```

Update recommended version to 1.19

---

CHANGELOG/CHANGELOG-2.0.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```

Add v2.0.1 release notes

---

CHANGELOG/CHANGELOG-2.0.md

Let's do a 2.0.2 to make this fix (or feature enhancement?) available...
```release-note
NONE
```

release notes for 2.0.2

---

CHANGELOG-1.6.md

Add change log for 1.6.1 release
Fixes #
```release-note
NONE
```
/cc @msau42

Add change log for 1.6.1 release

---

CHANGELOG-1.6.md

Update v1.6.1 changelog
Fixes #
```release-note
NONE
```
/cc @msau42

Update v1.6.1 changelog

---

CHANGELOG/CHANGELOG-2.0.md

Create change log for v2.0.3 patch release
Fixes #
```release-note
NONE
```
/cc @msau42

Create v2.0.3 change log

---

Dockerfile

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```

Cherry pick #503: Fix the failing multiarch builds

---

go.mod
go.sum
vendor/k8s.io/csi-translation-lib/go.mod
vendor/k8s.io/csi-translation-lib/go.sum
vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
vendor/modules.txt

/kind bug
upgrade azure translation lib to fix the azure file migration issue, related to https://github.com/kubernetes/kubernetes/pull/94904
Fixes #
```release-note
upgrade azure translation lib to fix the azure file migration issue
```

upgrade azure translation lib to fix the azure file migration issue

---

CHANGELOG/CHANGELOG-2.0.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```

Add changelog for v2.0.4

---

release-tools/prow.sh

Squashed 'release-tools/' changes from 5d874cce4..c6a88c6ed
c6a88c6ed Merge pull request #113 from xing-yang/install_snapshot_controller
45ec4c69f Fix the install of snapshot CRDs and controller
git-subtree-dir: release-tools
git-subtree-split: c6a88c6ed96b939bd150472b12693252942116c7

Update release tools2

---

CHANGELOG/CHANGELOG-2.1.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
/cc @msau42

Add changelog for release v2.1.0

---

CHANGELOG/CHANGELOG-2.1.md

We have accumulated several bug fixes for v2.1.0 which would be good to have in a patch release.
Fixes #563
```release-note
NONE
```

release v2.1.1

---

CHANGELOG/CHANGELOG-2.1.md

>
> /kind bug
> /kind design
> /kind flake
Use 2.1.1 instead of the branch name.
Fixes #
```release-note
NONE
```

Fix version in release notes

---

README.md

Signed-off-by: Dave Chen <dave.chen@arm.com>
>
/kind cleanup
Fixes #
```release-note
NONE
```

Update README.md where function name is incorrect

---

pkg/controller/controller.go

/kind bug
This PR uses the common lib to strip credentials in the logs.
Fixes #600
```release-note
NONE
```

Sanitize secrets in the requests

---

CHANGELOG/CHANGELOG-2.0.md

Updates documentation for v2.0.5 patch release.
Fixes #
```release-note
NONE
```

Add changelog for v2.0.5

---

pkg/controller/controller.go

/kind cleanup
Cherry-pick of 97bb65c450b71b5b238b9ad08794692947f6ae61 for the release-2.1 branch.
These are already logged as part of the gRPC connection.
Fixes #
```release-note
NONE
```

[release-2.1] Remove redundant log lines

---

CHANGELOG/CHANGELOG-2.1.md

Adds a changelog entry for v2.1.2.
Fixes #
```release-note
NONE
```
/assign @pohly 

[release-2.1] Add changelog for v2.1.2

---

pkg/capacity/topology/nodes.go

/kind cleanup
Code cleanup after PR #617.
Fixes #625
```release-note
NONE
```

capacity: simplify topology informer

---

cmd/csi-provisioner/csi-provisioner.go

/kind bug
Fix env name from POD_NAMESPACE to NAMESPACE for capacity-ownerref-level option
```release-note
Fix env name from POD_NAMESPACE to NAMESPACE for capacity-ownerref-level option.
```

Fix env name from POD_NAMESPACE to NAMESPACE for capacity-ownerref-level option

---

CHANGELOG/CHANGELOG-2.2.md

Let's do a v2.2.2 bug fix release to get some fixes into the hands of users.
I manually edited to change log items to point to the original PRs.
```release-note
NONE
```

release v2.2.2

---

README.md

Update snapshot support level in the readme to GA from beta

---

CHANGELOG/CHANGELOG-3.0.md
README.md

Adds the changelog for v3.0.0.
Fixes #
```release-note
NONE
```
/assign @msau42 
/assign @xing-yang

Add changelog for v3.0.0

---

CHANGELOG/CHANGELOG-3.1.md

Preparation for v3.1.0 / Kubernetes 1.24.
```release-note
NONE
```

Add changelog for v3.1.0

---

pkg/capacity/capacity.go

>
/kind bug
> /kind design
> /kind flake
`maximumVolumeSize` should be updated but not. 
NONE
NONE
NONE
```release-note
bug fix, no release-note
```

maximumVolumeSize should be updated when it changes

---

pkg/capacity/topology/nodes_test.go

/kind cleanup
When external-provisioner runs in central mode, it needs to collect topology
labels from CSINode and Node to determine which topology segments exist in the
cluster. This benchmark measures how well the code for that works for different
combinations of cluster size and number of segments (determined by the number
of nodes per segment). It measures that for the initial segment creation and
for a refresh where nothing changes.
benchstat shows that the numbers are stable (± 3%). The following script can be
used to turn the output of benchstat into a csv that can be imported into
Google Docs when using the configuration that iterates over node sizes from 0
to 10000 in steps of 100:
```
for t in initial refresh; …
```

capacity tracking: add benchmark for topology discovery

---

cmd/csi-provisioner/csi-provisioner.go
pkg/capacity/topology/nodes_test.go
pkg/controller/controller.go
pkg/controller/controller_test.go

Short declaration, variable declaration allignment and few other cleanups

---

OWNERS

/kind cleanup
I am going to help with releases, so it makes sense to also have the ability to
approve pending PRs.
I have admin rights in this repo.
```release-note
NONE
```

OWNERS: add pohly

---

deploy/kubernetes/storage-capacity.yaml

make use of latest provisioner controller in storage-capacity.yaml

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/support.md
.github/workflows/codespell.yml
CHANGELOG/CHANGELOG-1.4.md
pkg/capacity/provision.go
pkg/controller/controller_test.go
pkg/controller/topology_test.go

test: add codespell github workflow and templates for issues/RFEs.

---

pkg/controller/controller.go
pkg/controller/topology.go

Reference #https://github.com/kubernetes-csi/csi-release-tools/pull/203
-->
```release-note
NONE
```

correct the fmt errors on the controller files.

---

CONTRIBUTING.md

Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #786

Updated  CONTRIBUTING.md

---

CHANGELOG/CHANGELOG-3.3.md
README.md

This PR adds changelog for v3.3.
Fixes #
```release-note
NONE
```

Add changelog for v3.3

---

CHANGELOG/CHANGELOG-3.3.md

Update changelog for 3.3.0
Fixes #
```release-note
NONE
```

Update changelog for 3.3.0

---

deploy/kubernetes/storage-capacity.yaml

update sidecars to latest version

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go

/kind bug
Fixes #https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/121
```release-note
Fix stuck pod scheduled to a non exist node
```

Update sig-storage-lib-external-provisioner to v8.0.1

---

CHANGELOG/CHANGELOG-3.2.md

Fixes #
```release-note
NONE
```

Add changelog for v3.2.2

---

CHANGELOG/CHANGELOG-3.4.md

Fixes #
```release-note
NONE
```

Add changelog for v3.4.1

---

CHANGELOG/CHANGELOG-3.3.md

Fixes #
```release-note
NONE
```

Add changelog for v3.3.1

---

CHANGELOG/CHANGELOG-3.5.md

Fixes #
```release-note
NONE
```

Add changelog for 3.5.0

---

CHANGELOG/CHANGELOG-3.5.md

/kind cleanup
Fixes #
```release-note
NONE
```

Update csi-release tools

---

release-tools/build.make
release-tools/cloudbuild.yaml

/kind cleanup
Trying to fix multi-arch build failure
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-external-provisioner-push-images/1650918675659624448
Fixes #
```release-note
NONE
```

Update csi release tools

---

pkg/capacity/topology/nodes_test.go

/kind cleanup
https://github.com/kubernetes-csi/external-provisioner/issues/847 mentions a problem that occurs when the central controller runs before the node plugins. This should be handled through updating node segments and the code exists, it just lacked some unit tests. Those don't trigger the problem mentioned in the issue, but it's worthwhile to add them nonetheless.
Related-to #847
```release-note
NONE
```

capacity: more test cases

---

pkg/controller/controller_test.go

should replace loop with clientSetObjects = append(clientSetObjects, tc.secrets...)
Fixes #
```release-note
NONE
```

chore: slice replace loop

---

.github/dependabot.yaml

/kind cleanup
Groups is a beta feature and we need extra flag to enable the usage.
Fixes #
```release-note
NONE
```

Enable dependabot Beta Features

---

CHANGELOG/CHANGELOG-3.6.md

Add changelog for v3.6
Fixes #
```release-note
NONE
```

Add changelog for v3.6

---

release-tools/SIDECAR_RELEASE_PROCESS.md

update release-tools 

---

.github/dependabot.yaml

/kind cleanup
A few groups PR are failing so changing the logic https://github.com/kubernetes-csi/external-provisioner/pull/1027
Fixes #
```release-note
NONE
```
/assign @jsafrane

Adjust groups in dependabot

---

CHANGELOG/CHANGELOG-3.6.md

Fixes #
```release-note
NONE
```

Add changelog for 3.6.1

---

CHANGELOG/CHANGELOG-3.6.md

Add changelog for v3.6.2
Fixes #
```release-note
NONE
```

Add changelog for v3.6.2

---

CHANGELOG/CHANGELOG-3.6.md

Changelog for v3.6.3

---

CHANGELOG/CHANGELOG-4.0.md

Fixes #
```release-note
NONE
```

Add changelog for v4.0.0

---

release-tools/KUBERNETES_CSI_OWNERS_ALIASES
release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/generate_patch_release_notes.sh
release-tools/go-modules-update.sh
release-tools/prow.sh
release-tools/pull-test.sh

>
/kind cleanup
Squashed 'release-tools/' changes from de2fba88..dc4d0ae2
```
git subtree pull --squash --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master
```
Fixes #
```release-note
N/A
```

[release-3.6] Update release tools with go version fix

---

CHANGELOG/CHANGELOG-3.6.md

Changelog for v3.6.4

---

CHANGELOG/CHANGELOG-4.0.md

Changelog for v4.0.1

---

README.md

The old [link](https://github.com/kubernetes/design-proposals-archive/blob/main/storage/container-storage-interface.md) pointed to an archived page.

Update README.md: Add to new csi-driver docs

---

README.md
pkg/features/features.go

/kind feature
https://github.com/kubernetes/kubernetes/pull/123151 adds e2e tests.
Fixes #
```release-note
Promote HonorPVReclaimPolicy to beta.
```

promote HonorReclaimPolicy to beta

---

CHANGELOG/CHANGELOG-5.0.md
README.md

Update readme with topology GA support + add changelog for the next major release.
@xing-yang @msau42 
```release-note
NONE
```

Add changelog for v5.0

---

CHANGELOG/CHANGELOG-5.0.md

Add changelog for 5.0.1

---

CHANGELOG/CHANGELOG-5.0.md

Add changelog for v5.0.2.
```release-note
NONE
```

Add changelog for v5.0.2

---

pkg/controller/clone_controller_test.go

Looks like this was introduced later.

Fix race in tests

---

CHANGELOG/CHANGELOG-5.2.md

Add changelog for release v5.2.0
```release-note
NONE
```

Changelog for v5.2.0

---

CHANGELOG/CHANGELOG-5.3.md

Add changelog for a new release.
```release-note
NONE
```

Add changelog for 5.3
